### ISSUE TITLE
Return DB objects as pymongo directly.

### ISSUE THREAD

**Issue by doaa-altarawy** [MolSSI/QCFractal#101]
In strorage_socket, when approperiate, return query objects as_pymongo directly.
In this case, we will need to translate `_id` to `id`.
Notice that their will be no dereferencing to reference fields.

**Comment by dgasmith** [comment]
If I understand this correctly, this will return "raw" documents straight from pymongo without converting to ME Document classes?

**Comment by doaa-altarawy** [comment]
Yes. And since we never write without validation, then it's okay to read and deliver the pymongo results (by Mongoengine) without the intermediate validation.
Again, we should never write without ME in order to safely return as_pymongo()

**Comment by dgasmith** [comment]
This might be affected by https://github.com/MongoEngine/mongoengine/pull/1976

I didn't look into it too deeply, however.

**Comment by dgasmith** [comment]
This issue seems slightly out of date now that we always return pydantic objects.
