### ISSUE TITLE
Results documentation

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#11]
Several points to make:
 - Contains a *single* quantum chemistry execution (energy/gradient/Hessian/property)
   - Not a finite-difference gradient or geometry optimization (see procedures)
 - Uniquely define by (program, molecule_id, driver, method, basis, options).
   - ("psi4", "molecule_id", "energy", "b3lyp", "6-31g", "default")
 - Default execution engine is `qcengine.compute`.
 - Run completely on-node.

**Comment by mattwelborn** [comment]
Is this closed by PR #420?

**Comment by dgasmith** [comment]
Weakly, but yes.
