### ISSUE TITLE
Add GenericCollection

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#111]
Add a `GenericCollection` object which contains little to no structure allowing the user to fully define the underlying `data`. This would be used by other programs interacting with a FractalClient to control the computation and build internal structure appropriate for that program. An example here could be the SI2 DDD @loriab.

See [here](https://github.com/psi4/psi4/pull/1351).

**Comment by loriab** [comment]
By my understanding, if I ran a `ccsd/cc-pv[dt]z` calculation through QCFractal, the subsidiary SingleResult qcschemas for `ccsd/cc-pvdz` and `ccsd/cc-pvtz` have a rightful, and ultimately searchable, place in the QCA. This GenericCollection provides a place to lodge the parent `ccsd/cc-pv[dt]z` qcschema. It will be retrievable but not reusable, which is fine; at least it's somewhere.

**Comment by dgasmith** [comment]
I would presume a use case like:
```python
>>> id1 = client.submit(task_1)
>>> id2 = client.submit(task_2)

>>> data = {"label1": id1, "label2": id2}
>>> col = GenericCollection(name="mything", **data)
>>> client.save_collection(col)

# Come back at another point
>>> col = client.get_collection("generic", "mything")
>>> col
GenericCollection(name="mything", label1="id1", ...)

>>> client.get_results(id=[col.label1, col.label2])
```

So that the internal structure is completely up to you, more of a way to stash these things. We could add another table for this, but I am a bit hesitant to do so.

The reusability would be up to you and how you structure your code, as noted this is just a blank box.
