### ISSUE TITLE
Electrostatic potential and electric field on a grid

### ISSUE THREAD

**Issue by leeping** [MolSSI/QCFractal#117]
For our Open Force Field collaboration, we would like for calculations to be able to output electrostatic potential (ESP) and electric field (EF) values on a grid.  

There are a few standard ways of generating grids for evaluating ESPs, such as Merz-Singh-Kollman grids, which are standard in the AMBER procedure, and Christopher Bayly's FCC grids.  The [respyte package](https://github.com/lpwgroup/respyte), which @hyejang is developing in my group, should contain methods for easily generating these grids for a provided molecular structure (i.e. atomic symbols and xyz coordinates).  Our current idea is for QCArchive to interface with `respyte` to generate the grid points, then call the QC code to evaluate the ESPs and electric fields.  

The potential applications of this feature would be the development of a wide range of electrostatic models, including point-charge, multipole, and polarizable.  To support all of these, we should be able to compute ESPs and EFs for any structure (including optimized, constrained-optimized and un-optimized.)  For developing polarizable models, it would be highly helpful if we could place external point charges near the molecule.  The external point charge would polarize the electron density which would affect the ESP/EF.  However, I think the output ESP/EF should not contain the "direct" contribution from the external point charge, as it may be very close to the grid points and result in very large values. 

Note: QCArchive would not be responsible for producing the charge model (i.e. running RESP), as we would do that locally.  Once we have decided on a good charge model and a more solid procedure, we could talk about having QCArchive carry out the RESP fitting in a separate feature.

**Comment by leeping** [comment]
@hyejang has provided a spreadsheet that summarizes the number of grid points for a number of molecules (various amino acid dipeptides, such as ACE–SER–NME).

https://docs.google.com/spreadsheets/d/1OOtH-BjvyMQMQ3EZGQzko00RHIJzOO8jc0LRNP_YBws/edit?usp=sharing

The standard MSK scheme with four spherical layers of points at (1.4, 1.6, 1.8, 2.0)*r_vdw has an average of 93 grid points per heavy atom for the molecules considered.  The FCC scheme with the same inner and outer radii has 98 grid points per heavy atom.  

Also: We would like to use a FCC "super-grid" with a larger range of radii, ranging from 0.8*r_vdw to 2.4*r_vdw (this is @cbayly13 's idea).  As the FCC grid points can be "pruned" at fitting time, this will enable us to research the effects of changing the grid size - for example, if we wanted to include slightly closer or slightly farther grid points - without having to re-generate the grid and recompute the ESPs.    The number of grid points per heavy atom for the "super-grid" is 259.

**Comment by leeping** [comment]
@dgasmith and I just talked, and we agreed to move forward by having the user pass a list of grid points as input to the calculation.  In the future when respyte becomes more stable, we could revisit having QCArchive ask it for the grid points.

**Comment by dgasmith** [comment]
Do you have a timeline when you would like to start these ESP computations?
