### ISSUE TITLE
Handle Optimization options uniqueness

### ISSUE THREAD

**Issue by doaa-altarawy** [MolSSI/QCFractal#122]
**Description**

Currently, the optimization procedure is almost unique by a hash_index created by fractal using the fields:

- Procedure (procedure type which is "optimization")
- program (procedure program)
- Keywords (can be any JSON structure and can differ by a very small number.
- initial_molecule
- qc_meta: the 5 unique keys of a Result without mol (program, method, driver, basis, options)

Users will lookup procedures by their IDs through collections and services. But in the case of submitting a new procedure, we need to make sure it doesn't exist to avoid duplicate submissions by mistake.
This check is currently done by the hash_index.

**Possible solutions**

Hash the keywords only, putting into consideration that enries can be very similar. The other option is to keep the current hash_index but make sure all fields exist in the procedure document (by saving using ME classes).

**Comment by dgasmith** [comment]
I think you captured this nicely. As mentioned the only duplicate case we are really after is preventing a user from submitting the same optimization twice with same script. A keyword hash will pick up the difference between a float of `1.e-15` and `1.e-16` as long as it does not pre-round values to some value like `1.e-10`. The current hashing tech works for the this particular use case, but no real attachment to it. 

I think at some point you mentioned ME has hashing tech for arbitrary dictionaries? A MD5 of `json.dumps(data, sort_keys=True)` should likely be good.

**Comment by dgasmith** [comment]
Ok, this seem fine where we build our own hash indices. And not allowing a hash index to be unique seems quite reasonable as it is not a promise that can be made.

When they truncate floats, what tolerance do they do this too?

**Comment by dgasmith** [comment]
This is likely closed by #183 with checks like [this](https://github.com/MolSSI/QCFractal/pull/183/files#diff-0f022d5c1bb573e38477fff783235a31R191). The documents themselves generate a pseudo unique hashes based off a recursive canonicalization algorithm.

**Comment by dgasmith** [comment]
I think #183 closed this issue, we can revisit if needed at a later date.
