### ISSUE TITLE
Verify all dependency trees and min version requirements

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/QCFractal#134]
**Describe the bug**
Every dependency specification: `setup.py`, `meta.yaml`, and conda-env files need to be combed through carefully to make sure we are:
1. Pulling the package from the most correct source
2. Minimum versions are correctly pinned
3. Package versions from the correct source are updated to the correct minimal version.

**Comment by dgasmith** [comment]
@Lnaden Make sure to close this when you feel comfortable.

**Comment by Lnaden** [comment]
Can confirm. Fresh environments building form both pip and conda-forge have everything working (for the packages that are there). All dependencies check out and tests pass. 

This marks the final 0.5.0 issue. Release imminent
