### ISSUE TITLE
Project Snowflake

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#148]
One request that I often see is if we can make a new Fractal instance very easily that is *explicitly* temporary. As MongoDB startup is lightning fast (0.06 seconds) and we can use temporary directories this is fairly easy to do:

```
tmpdir = tempfile.TemporaryDirectory()
mongo_args = ["mongod", "--dbpath", tmpdir.name, "--port", str(port)]

with qcfractal.testing.popen(mongo_args):
    time.sleep(1)
    client = pymongo.MongoClient("localhost:" + str(port))
```

I think we would have a signature like the following:
```
client = qcfractal.Snowflake(dbpath=None)
```

which would have the `interface.FractalClient` attributes plus a few things like `await_results` so that a user can let a result complete. A typical use case would to use this in a Jupyter notebook to explore a bit before running a real instance.

Thoughts?

**Comment by Lnaden** [comment]
Interesting idea, I'm not entirely sure about the use case though. What data would you explore with a Fractal instance which just popped up (I would assume it has no data populated)?

**Comment by dgasmith** [comment]
It would be more of an easy way of trying out the whole ecosystem. I think this level of data persistency is hard to wrap your head around and we have a lot of asks for the ability to loose data when trying things out. We may also consider `server = qcfractal.FractalServer(temporary=True)` with big warning lights. I mostly wanted a different name to be *very* clear that the data was not persistent.

**Comment by Lnaden** [comment]
> I think this level of data persistency is hard to wrap your head around and we have a lot of asks for the ability to loose data when trying things out.

That makes sense. I'm all for it then

> We may also consider `server = qcfractal.FractalServer(temporary=True)` with big warning lights. I mostly wanted a different name to be _very_ clear that the data was not persistent.

I think `.Snowflake` is a safer, and more explicit way of doing it than a keyword. Do that instead of `temporary=True` so there is no chance someone gets it wrong
