### ISSUE TITLE
Check result duplicates

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#151]
We need to check a few possible "gotchas" when submitting results:
 - A basis of `None`, `""`, and other similar instances of None should be the same.
 - A option key of `None` and `{}` should be equivalent to each other as well.
 - Program, basis, driver should always be lowercase.

These should be pushed to None ('null') lookups.

**Comment by Lnaden** [comment]
We should be able to wrap most of these with a `if not ({object} is False or {object}):` statement to trap all the "empty" objects which we can test against, while also not accidentally setting a literal `False` to `None`

**Comment by dgasmith** [comment]
At this point these are simple fields that should explicitly be `Optional[str]` at this layer, so bools or objects cannot be present. This will need to happen both at the database add and database query layers.
