### ISSUE TITLE
REST and Schema documentation style

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#16]
Current schema documentation style should be improved as the [current version](https://molssi-qc-schema.readthedocs.io/en/latest/auto_topology.html) is perhaps not the most optimal. Several options could be:
 - [Foldable options](http://getyank.org/latest/yamlpages/options.html)
 - [Bootprint](https://github.com/bootprint/bootprint-json-schema)
 - [Swagger.io](https://petstore.swagger.io)
 - [Stripe](https://stripe.com/docs/api?utm_source=zapier.com&utm_medium=referral&utm_campaign=zapier)

Most of these options are build for REST endpoints (which we have). However, we also have pure "schema" such as the QCSchema that would be nice to present in a precise syntax.

Anyone have an opinion or additional options to examine?

**Comment by Lnaden** [comment]
I would avoid using the foldable/collapsable styles for doing auto-gen things. What you linked from the YANK project are all the YAML options and documentation which I had write and link manually. There is an auto-gen API docs we use for the API, but I have never found the Sphinx autodoc modules to be that good for complex projects.

**Comment by dgasmith** [comment]
I have been toying around with the idea of having pydantic classes as REST requests/responses templates. The benefit here is several fold:
- We can automatically validate requests 
- We can return consistent validation errors across all models
- We can automatically export pydantic to jsonschema for Swagger.io-style docs (which I think we should lean on)
- We keep a consistent object model across the project.

Thoughts?

**Comment by loriab** [comment]
I've had minimal experience with pydantic, but what I've had I've liked. Prevents me from adding undeclared things to `self`. Prevents me from appending to wrong level of dict. If pydantic lets me write less json schema docs directly, and nicely extends to generating good stuff I'm even less acquainted with (e.g., REST), I'm for it.

**Comment by dgasmith** [comment]
Related to #330.

**Comment by dgasmith** [comment]
Closed in https://github.com/MolSSI/QCFractal/pull/349.
