### ISSUE TITLE
Figure out Parsl Process killing not working

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/QCFractal#164]
**Describe the bug**
#156 testing revealed that Parsl does not correctly shutdown all its workers, resulting in an ever growing list of open files.

Any tests run with the Parsl fixtures (and I imagine the Parsl Adapter in general) don't close the Executors correctly. When the "shutdown-like" commands are called, the following block in `parsl/executors/ipp_controller.py(154)close()` is called 

```python
        try:
            pgid = os.getpgid(self.proc.pid)
            os.killpg(pgid, signal.SIGTERM)
            time.sleep(0.2)
            os.killpg(pgid, signal.SIGKILL) # <---- This line fails
            try:
                self.proc.wait(timeout=1)
                x = self.proc.returncode
                if x == 0:
                    logger.debug("Controller exited with {0}".format(x))
                else:
                    logger.error("Controller exited with {0}. May require manual cleanup".format(x))
            except subprocess.TimeoutExpired:
                logger.warn("Ipcontroller process:{0} cleanup failed. May require manual cleanup".format(self.proc.pid))

        except Exception as e:
            logger.warn("Failed to kill the ipcontroller process[{0}]: {1}".format(self.proc.pid, e))
```

which throws `PermissionError: [Errno 1] Operation not permitted`. The end result is that a large number of processes executed by `parsl` bash scripts, `ipengine`, and `ipcontroller` remain running and are never shut down. On its own, this is bad enough, but then they also retain access to open files to the MongoDB. (I view them through `lsof -iTCP -sTCP:LISTEN -n -P`), eventually getting the OS to throw a system wide error of Too Many Open Files, causing all kinds of problems at a system-wide level, including preventing MongoDB from shutting down and restarting correctly.

I have not had a chance to dig into this any more than what I found in testing but wanted to make an issue on it. Until we find a proper solution, the Parsl tests are disabled. 

In order to clean up the system, I had to run the following:
`for parslid in parsl ipengine ipcontroller; do for pid in $(ps -ef | grep "$parslid" | awk '{print $2}'); do kill -9 $pid; done; done`

**To Reproduce**
Use the Parsl Adapter

**Expected behavior**
Files should not be open.

**Additional info**
* I have only tested this on my local OSX machine.
* QCFractal specifically uses `parsl.dataflow.dflow.DataFlowKernel` as its client
* The local machine uses the Parsl IPController to execute its jobs.

edit: added additional info

**Comment by Lnaden** [comment]
Related issue #170, this is a workaround to this issue, thanks to @dgasmith for helping test this.

We were able to find out that its only the IPyParallelExecutor, running in PyTest (unknown conditions). Production is safe. For now, switching to the `ThreadPoolExecutor` and making it thread safe works around the problem. This issue will remain open, but lower priority as we will need to further isolate this to report to the Parsl team, but its no longer blocking.

`pkill python` to kill the threads also works, but is more aggressive than my double for loop in the original post.

**Comment by dgasmith** [comment]
Highly possible this is related to PyTest's manipulations. Trying the following seems fine however:
```
import pytest
from parsl.configs.local_ipp import config
from parsl.dataflow.dflow import DataFlowKernel
from parsl.app.app import python_app

@pytest.fixture()
def kernel():
    kernel = DataFlowKernel(config)
    yield kernel

def test_task(kernel):

    def internal_func(s):
        return "Hello! {}".format(s)
    func = python_app(internal_func, data_flow_kernel=kernel)

    a = func("Hi!")
```

**Comment by Lnaden** [comment]
This appears to be Pytest + IPyParallelExecutor combination which we don't use anymore and has not cropped back up since. I am going to close this issue as I don't think its something we need to worry about as Fractal.
