### ISSUE TITLE
Make API website access through standard browsers more helpful

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/QCFractal#200]
We have a public DNS now at `api.qcarchive.molssi.org`, yay! This is helpful for Tornado based communication from a Client instance, but has some placeholder objects when accessing it through a browser:

api.qcarchive.molssi.org goes to a standard NGiNX webpage. We should probably point this to the docs or the upcoming Hugo page.

`api.qcarchive.molssi.org:443` (or any non-dedicated port) points to a 400 error due to pointing a HTTP request at an HTTPS location

`https://api.qcarchive.molssi.org:433` (or any non-dedicated port) actually gives us a traceback error, nothing is revealed, but still interesting
```python
Traceback (most recent call last):
  File "/home/dgasmith/miniconda3/envs/qcf/lib/python3.7/site-packages/tornado/web.py", line 1569, in _execute
    result = self.prepare()
  File "/home/dgasmith/miniconda3/envs/qcf/lib/python3.7/site-packages/tornado/web.py", line 2322, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```

I'm not sure if we should change the pointers here, or how to for that mater, but something to consider.

**Comment by dgasmith** [comment]
This has been changed to "Bad Gateway". Check out our websites for better web-based data inspection.
