### ISSUE TITLE
Case sensitivity of collection names

### ISSUE THREAD

**Issue by janash** [MolSSI/QCFractal#201]
When querying collections, the collection name is case sensitive, while the collection class is not. Both should be case insensitive.

Following the "Getting Started" documentation....

Both `client.list_collections("reactiondataset")` and `client.list_collections("ReactionDataset")` work (ie - case doesn't matter).

However, `client.list_collections("reactiondataset", "s22")` fails while  `client.list_collections("reactiondataset", "S22")` returns the intended collection.

**Comment by dgasmith** [comment]
I don't know of a better way to handle this besides having a `display name` and a `query name` or similar. @doaa-altarawy any thoughts here on good ways to mix case sensitive display names and case insensitive query names?
