### ISSUE TITLE
Additional metadata for datasets

### ISSUE THREAD

**Issue by janash** [MolSSI/QCFractal#202]
It would be useful to be able to see descriptions of the datasets by querying QCFractal. 

Some suggested additional metadata (added as additional keywords to what is currently returned):

- Description of the dataset (an additional key added to the collection)
`ReactionDataset(name=`S22`, id='5c8159a4b6a2de3bd1e74306', client='https://api.qcarchive.molssi.org:443/', description="short description here")`

- Tags added to dataset. 
`ReactionDataset(name=`S22`, id='5c8159a4b6a2de3bd1e74306', client='https://api.qcarchive.molssi.org:443/', tags=[list of tag words])`

- Reference data
`ReactionDataset(name=`S22`, id='5c8159a4b6a2de3bd1e74306', client='https://api.qcarchive.molssi.org:443/', doi='doi')` 

Adding the ability to query by these values would be useful. For example, the user may want to pull datasets relevant to biomolecules.

Currently, collections are retrieved by type and name, for example
`client.get_collection("reactiondataset")`, could something be added so that `client.get_collection("reactiondataset", tag="biomolecule")`?

 Exact UI would have to be decided.

**Comment by dgasmith** [comment]
+1 for this, maybe have a `tagline` attribute as well. @loriab @dnascimento13 any thoughts here?

**Comment by loriab** [comment]
here's some taglines

```
dataset_choices = collections.OrderedDict()
dataset_choices['S22'] = """interaction energies for organic bimolecular complexes"""
dataset_choices['NBC10'] = """interaction energies for dissociation curves of dispersion-bound bimolecular complexes"""
dataset_choices['HBC6'] = """interaction energies for dissociation curves of doubly hydrogen-bonded bimolecular complexes"""
dataset_choices['HSG'] = """interaction energies for bimolecular complexes from protein-indinavir reaction site 1HSG"""
dataset_choices['DB4'] = """equal weight of S22, NBC10, HBC6, and HSG"""
dataset_choices['UBQ'] = """interaction energies for bimolecular complexes from native 1UBQ protein fold"""
dataset_choices['BBI'] = """interaction energies for peptide backbone-backbone complexes"""
dataset_choices['SSI'] = """interaction energies for peptide sidechain-sidechain complexes"""
dataset_choices['A24'] = """interaction energies for small bimolecular complexes"""
dataset_choices['S22by7'] = """interaction energies for dissociation curves of organic bimolecular complexes"""
dataset_choices['S66'] = """interaction energies for organic bimolecular complexes"""
dataset_choices['ACONF'] = """conformation energies for alkanes"""
dataset_choices['CYCONF'] = """conformation energies for cysteine"""
dataset_choices['PCONF'] = """conformation energies for tripeptides"""
dataset_choices['SCONF'] = """conformation energies for sugars"""
dataset_choices['ACHC'] = """interaction energy curves for adenine-cytosine stacked nucleobases through six translations and rotations"""
dataset_choices['JSCH'] = """interaction energies for nucleobase pairs"""
dataset_default = 'S22'
```

**Comment by dgasmith** [comment]
This has been done thanks to hard work from @loriab, @dnascimento13, and Dom. This now looks like the following:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1769841/55279750-60bbe280-52f2-11e9-9323-b058dccabd27.png">
