### ISSUE TITLE
Check base MongoDB version

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#22]
The base MongoDB version should be checked:

```
>>> client = pymongo.MongoClient()
>>> client.server_info()["version"]
'3.4.4'
```

**Comment by geeksambhu** [comment]
Could not find the documentation. Where is it needed to be checked?

**Comment by dgasmith** [comment]
In the `init` of the MongoSocket (https://github.com/MolSSI/QCFractal/blob/master/qcfractal/db_sockets/mongo_socket.py#L42) would be best. Minimum version is 3.2 if I recall correctly.

**Comment by Lnaden** [comment]
Why the `init` and not the Import?

**Comment by dgasmith** [comment]
The import of `pymongo` is independent of the version of the MongoDB instance running. Proper pinning will get the pymongo version correct, but we need to explicitly check to ensure we are not hitting an old compilation of MongoDB.
