### ISSUE TITLE
Conda env channel changes

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#23]
Conda-forge is the primary channel used for all environments; this is not needed as Anaconda has pulled the majority of the packages back upstream. Also, conda-forge NumPy and Psi4 has conflicts as cf uses OpenBLAS. This does not appear to be an issue, but no reason to have multiple BLAS libraries in the possible conflict.

**Comment by loriab** [comment]
I don't think that first sentence is quite right. More like anaconda defaults and c-f have agreed to share recipes and build toolchain to ensure future compatibility or stacks. It may even be that defaults builds slightly fewer packages, separating core anaconda from community packaging.

But +1 on looking into the correct mkl/defaults/c-f mix in future.

**Comment by dgasmith** [comment]
Hmm, that is interesting. Regardless they have packages like `psutil` on defaults now which is great. Cuts down on a lot of the c-f requirements for "smaller" packages.
