### ISSUE TITLE
Crank Interface

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#25]
Requirements gathering for interaction with a Crank result.

Search capabilities:
 - Search by id
 - Search by initial molecule (geometry information included) and SMILES.
 - Search by QM method, program, basis, and options

Required information:
 - Computational details (method, program(s), basis, molecule)
 - Lowest energy at each grid point
 - Lowest energy final trajectory at each grid point.
 - Trajectory "history" at each grid point.

@yudongqiu @ChayaSt can you fill in the details of your requirements here?

**Comment by dgasmith** [comment]
Current example:
```python
>>> import qcfractal.interface as portal

>>> client = portal.FractalClient(server_address)

# Search for Crank results, grab the first
>>> result = client.get_service(query)[0]
>>> print(result)
TorsionDrive(id='5b85c5a17b878733c7dbbbee', state='FINISHED', molecule_id='5b85c5a07b878733c7dbbbed', molecule_name='HOOH')

>>>  print(result.final_energies())
{(-90,): 0.00015655376185927123, (180,): 0.0007534925560578865, (0,): 0.002597541340221565, (90,): 0.0001565537618592763} # UFF results so energies are positive.
```

**Comment by ChayaSt** [comment]
We also want to be able to search:

- standard SMILES (without the geometry) so we can get all tautomers / ionization / protonation states associated with this molecular graph.

- Workflow used to generate this set of fragments.

**Comment by dgasmith** [comment]
I can add point 1).

For point 2) I think we want to build associativity the other way where a Workflow database entry is made which references all crank jobs.

**Comment by dgasmith** [comment]
The Crank API has evolved over time and currently meets all use cases. This issue as it stands is not serving a purpose and will be closed. Please create new issues focusing on specific feature requests.
