### ISSUE TITLE
Database Upgrade System and Plan

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/QCFractal#252]
When the database changes (such as hash/index calculation changes), we need to have a formal mechanism and procedure for detecting not only server mismatch, but providing an upgrade path.

Related to #245

Proposed PR Actions (based on discussion):
* Add field(s) to Database which tracks all the versions of libraries this database was generated with which affect hashing and indexing.
* Specify in `FractalServer` the minimum and maximum versions of all the libraries tracked in the database (from last point) which are compatible with the server version (since its the thing hashing)
* Throw an error if there is a version mismatch and do not allow the server to boot. Point the user at an upgrade script location
* Write an upgrade script which connects directly to the socket and converts a database written from dependency set `X` -> dependency set `Y`. Ship these with Fractal.
    * Allow server rollback in case something goes wrong
* Allow server to start after database upgrade applied

**Comment by dgasmith** [comment]
Closed by https://github.com/MolSSI/QCFractal/pull/312.
