### ISSUE TITLE
Enhanced manager reporting

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#262]
**Is your feature request related to a problem? Please describe.**
Managers should log their current resource consumption and several metrics on their cumulative consumption. This will allow manager maintainers to obtain a quick overview of consumed resources and also investigate potential issues.

**Describe the solution you'd like**
Every several minutes in the `qcfractal-manager` logs print out the following:
 - Approximate number of nodes, cores, and memory that the manager is consuming. This data can be pulled from most distributed managers by querying the number of active workers.
 - Approximate total number of core-hours consumed since manager boot up. A good approximation is total number of current core * update interval. This does not have to be incredibly accurate, but more to give a general guideline.
 - The number of pulled, completed, batched returned tasks, and failed tasks periodically.

This information would also be very useful to push back to the server, but should be a future step.

**Additional context**
Related to #261.

**Comment by Lnaden** [comment]
Should be fixed by #313
