### ISSUE TITLE
qcfractal-manager --help throws an error

### ISSUE THREAD

**Issue by jchodera** [MolSSI/QCFractal#287]
**Describe the bug**
```
(snowflake) jchodera1@titan-ext2:/lustre/atlas/scratch/jchodera1/chm126/qcfractal> qcfractal-manager --help
Traceback (most recent call last):
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda/envs/snowflake/bin/qcfractal-manager", line 6, in <module>
    from qcfractal.cli.qcfractal_manager import main
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda/envs/snowflake/lib/python3.7/site-packages/qcfractal/cli/qcfractal_manager.py", line 419, in <module>
    cli_utils.doc_formatter(ParslQueueSettings)
  File "/lustre/atlas/scratch/jchodera1/chm126/miniconda/envs/snowflake/lib/python3.7/site-packages/qcfractal/cli/cli_utils.py", line 140, in doc_formatter
    prop_type = prop["type"]
KeyError: 'type'
```
**To Reproduce**
```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p miniconda
# install miniconda in shell
conda install --yes anaconda-client
conda env create qcarchive/qcf-snowflake -n snowflake
conda activate snowflake
qcfractal-manager --help
```

**Expected behavior**
The command help would be returned.

**Additional context**
<details>
  <summary>Click to expand conda environment info</summary>
<pre>
(snowflake) jchodera1@titan-ext2:/lustre/atlas/scratch/jchodera1/chm126/qcfractal> conda list
# packages in environment at /lustre/atlas/scratch/jchodera1/chm126/miniconda/envs/snowflake:
#
# Name                    Version                   Build  Channel
ambit                     0.3                  h137fa24_1    psi4
asn1crypto                0.24.0                   py37_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
backcall                  0.1.0                    py37_0  
bcrypt                    3.1.6            py37h7b6447c_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
boost                     1.70.0           py37h9de70de_1    conda-forge
boost-cpp                 1.70.0               ha2d47e9_0    conda-forge
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.5.15                     0  
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0  
cffi                      1.12.3           py37h2e261b9_0  
chardet                   3.0.4                    py37_1  
chemps2                   1.8.9                h8c3debe_0    psi4
cryptography              2.7              py37h1ba5d50_0  
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                    py37_1  
deepdiff                  4.0.6                      py_0    conda-forge
defusedxml                0.6.0                      py_0  
dkh                       1.2                  h173d85e_2    psi4
entrypoints               0.3                      py37_0  
expat                     2.2.6                he6710b0_0  
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.9.1                h8a8886c_1  
gau2grid                  1.3.1                h035aef0_0    psi4
gdma                      2.2.6                h0e1e685_6    psi4
geometric                 0.9.7.2                    py_0    conda-forge
gettext                   0.19.8.1             hd7bead4_3  
glib                      2.58.3            hf63aee3_1001    conda-forge
gmp                       6.1.2                h6c8ec71_1  
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
importlib_metadata        0.17                     py37_1  
intel-openmp              2019.4                      243  
ipykernel                 5.1.1            py37h39e3cac_0  
ipython                   7.5.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10.1                   py37_0  
jpeg                      9c                h14c3975_1001    conda-forge
jsonpickle                1.1                        py_0  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
krb5                      1.16.1               h173b8e3_7  
libcurl                   7.64.1               h20c2e04_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15                 h63c8f33_5  
libint                    1.2.1                hb4a4fd4_6    psi4
libpng                    1.6.37               hbc83047_0  
libpq                     11.2                 h20c2e04_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxc                     4.3.4                h9ac9557_0    conda-forge
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
markupsafe                1.1.1            py37h7b6447c_0  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
mongodb                   4.0.3                h597af5e_0  
mongoengine               0.18.0                   py37_0    conda-forge
more-itertools            7.0.0                    py37_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.3                        py_0  
notebook                  5.7.8                    py37_0  
numpy                     1.16.4           py37h7e9f1db_0  
numpy-base                1.16.4           py37hde5b4d6_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1c               h7b6447c_1  
ordered-set               3.1.1                      py_0    conda-forge
packaging                 19.0                     py37_0  
pandas                    0.24.2           py37he6710b0_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.4.0                      py_0  
pcmsolver                 1.2.1            py37h142c950_0    psi4
pcre                      8.43                 he6710b0_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.0.0            py37h34e0f95_0  
pint                      0.9                      py37_2    conda-forge
pip                       19.1.1                   py37_0  
pixman                    0.34.0               hceecf20_3  
plotly                    3.10.0                     py_0  
pluggy                    0.12.0                     py_0  
prometheus_client         0.6.0                    py37_0  
prompt_toolkit            2.0.9                    py37_0  
psi4                      1.3.2+ecbda83    py37h31b3128_0    psi4
psutil                    5.6.2            py37h7b6447c_0  
psycopg2                  2.7.6.1          py37h1ba5d50_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    py37_0  
py-cpuinfo                5.0.0                      py_0  
py3dmol                   0.8.0                      py_0    conda-forge
pycairo                   1.18.1           py37h2a1e443_0  
pycparser                 2.19                     py37_0  
pydantic                  0.28                     py37_0    conda-forge
pygments                  2.4.2                      py_0  
pymongo                   3.8.0            py37he6710b0_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.14.11          py37h7b6447c_0  
pysocks                   1.7.0                    py37_0  
pytest                    4.6.2                    py37_0  
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                    py37_0  
pytz                      2019.1                     py_0  
pyyaml                    5.1              py37h7b6447c_0  
pyzmq                     18.0.0           py37he6710b0_0  
qcelemental               0.4.1                      py_0    conda-forge
qcengine                  0.6.4                      py_0    conda-forge
qcfractal                 0.7.2                      py_0    conda-forge
qcportal                  0.7.2                      py_0    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
qtconsole                 4.5.1                      py_0  
rdkit                     2019.03.2        py37hb31dc5d_1    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_0  
retrying                  1.3.3                    py37_2  
send2trash                1.5.0                    py37_0  
setuptools                41.0.1                   py37_0  
simint                    0.7                  h642920c_1    psi4
sip                       4.19.8           py37hf484d3e_0  
six                       1.12.0                   py37_0  
sqlalchemy                1.3.4            py37h7b6447c_0  
sqlite                    3.28.0               h7b6447c_0  
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                hbc83047_0  
tornado                   6.0.2            py37h7b6447c_0  
traitlets                 4.3.2                    py37_0  
urllib3                   1.24.2                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.33.4                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1                he6710b0_3  
zipp                      0.5.1                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 
</pre>
</details>

**Comment by Lnaden** [comment]
This appears to be something which the new Pydantic release changed the way it presents it objects. My doc formatting helper function broke. If you need a very quick work around you can change the `cli.cli_utils.doc_formatter` function to just `return` instead of doing anything. That would require the fewest line changes. I'll work on a fix today.

**Comment by Lnaden** [comment]
You can also downgrade Pydantic to 0.26 and have everything work correctly too.

**Comment by dgasmith** [comment]
I can reach out to Pydantic to see if we can push the auto docs  upstream. Seems worthwhile for many users and less prone to breaking.

**Comment by jchodera** [comment]
> You can also downgrade Pydantic to 0.26 and have everything work correctly too.

Would be good to update the conda build with a pinned pydantic.

**Comment by dgasmith** [comment]
Always better to fix, bump package patch version, and boost Pydantic minimum then pin versions.
