### ISSUE TITLE
Adapter options in config files

### ISSUE THREAD

**Issue by jeffschriber** [MolSSI/QCFractal#288]
When I run a manager using either Dask or Parsl adapters, I am required to specify some options, i.e.,
```
parsl:
  provider:
    cmd_timeout: 30
```
If no options are present, I see errors like,
`AttributeError: 'NoneType' object has no attribute 'provider'`. Relatedly, I'm not so sure which options I should be using in these blocks.
 
**To Reproduce**
Start any qcfractal-manager with no parsl/dask options specified in the config file

**Expected behavior**
I expect a default parsl/dask object to be created instead of the errors with `Nonetype` that are produced

**Comment by Lnaden** [comment]
The choice of the `common.adapter` setting impacts the other top level blocks you may need for Parsl and/or Dask.

>  expect a default parsl/dask

Part of the problem I had with this block is that instancing this is that the Cluster, Dask, and Parsl blocks tend to be so specific to the exact hardware you are running on that setting defaults of any kind runs the very high risk of setting the wrong defaults which make no sense, and then cause additional confusion for the user who then has an adapter just blindly start consuming resources.

There are a couple of different approaches I can take here, I'd like your opinion on what you would prefer:

1. Default settings, with the known assumption that many of them will likely not apply to your hardware, but at least won't throw a python-level error
2. Much more clear error message (which I admit the one you have isn't helpful) but still require the user to actually set a parsl/dask block?

**Comment by dgasmith** [comment]
I think 1) as #291 completed. There are some simple cases where the extra workflow specific config is not required. 2) would also help where possible :)

**Comment by Lnaden** [comment]
I'll close this as #291 handled most of this issue, and should prevent that particular error from here. As we find more unhelpful errors, we can clean those up in separate issues and PRs
