### ISSUE TITLE
qcf launch docs improvements

### ISSUE THREAD

**Issue by loriab** [MolSSI/QCFractal#289]
Herein are notes on improvements to documentation as gathered from testers at GT.

**Comment by dgasmith** [comment]
Submitting geometry optimizations with incorrect top level keys returns a internal server error rather than a pydantic validation error:

```python
spec = {"": None, "qc_spec": ...}
```

**Comment by loriab** [comment]
* is it simple to add in a new database?
* do you want more databases?
* `qc ` with space in Google doesn't hit molssi tools
* am I targeted as a qcf user?
* near "all data will be lost warning" need link to how to set up a server pemanently
* define "snowflake". may just need to fix formatting.
* in the tutorial?, don't name the conda env "snowflake", as that's confusing.
* quickstart tutorial, input [6], rename dict from `options` to `spec`?
* when new qcf term introduced, provide link to API docs

**Comment by mattwelborn** [comment]
@dgasmith ping. Let me know which of these should be addressed for 0.9.0.

**Comment by dgasmith** [comment]
@mattwelborn Get to what you can, lower priority than other items I think.

**Comment by mattwelborn** [comment]
@loriab I know your comment was from a while ago, but could you please elaborate on some of these points (if you can remember)?

> is it simple to add in a new database?

Does this refer to adding a new pre-computed dataset? To the MolSSI instance or to a private instance?

> do you want more databases?

This refers to users contributing their data to the MolSSI instance?

**Comment by mattwelborn** [comment]
I'm going to close this issue since PR #366 is merged. The rest of the feedback is now in issue MolSSI/QCArchiveWebsite#35.
