### ISSUE TITLE
Implement molecule.to_file

### ISSUE THREAD

**Issue by j-wags** [MolSSI/QCFractal#294]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a single function that can write a QCArchive molecule out to a file.

**Describe the solution you'd like**
Something like `my_molecule.to_file('example.xyz', format='xyz')` would be ideal.

**Describe alternatives you've considered**
```
with open('example.xyz', 'w') as of:
    of.write(my_molecule.to_string('xyz'))
```

**Comment by dgasmith** [comment]
Easy to do, we will look into it!

**Comment by loriab** [comment]
how does a write-string-to-file wrapper around https://github.com/MolSSI/QCElemental/blob/master/qcelemental/molparse/to_string.py#L9-L47 look?

**Comment by dgasmith** [comment]
That was the plan. We can do something slightly fancier:

```python
def to_file(filename, dtype=None):
    if dtype is None:
        if filename.endswith("xyz"):
           dtype = "xyz"
         ...

    with open(filename, 'w') as handle:
        handle.write(my_molecule.to_string(dtype))

```

**Comment by dgasmith** [comment]
Added to Elemental. Should be available next release.
