### ISSUE TITLE
Restarting specific jobs

### ISSUE THREAD

**Issue by jeffschriber** [MolSSI/QCFractal#304]
**Is your feature request related to a problem? Please describe.**
A development branch of Psi4 currently uses a straightforward interface to QCFractal via,
```
r = client.add_compute("psi4", self.method, self.basis, self.driver, keyword_id, [mol])
self.result_id = r.ids[0]
if self.result_id in r.existing:
    print("Job already completed {}".format(self.result_id))
else:
    print("Submitting Single Result {}".format(self.result_id))
```

The results are collected with,
```
result = client.query_results(id=self.result_id)
```

If a calculation fails for some reason, so that the job status becomes `ERROR`, it cannot be restarted with the above calls. 

**Describe the solution you'd like**
I know job restarts are possible from the server-level, but it would be convenient to somehow rerun any job regardless of its current status. Maybe something like,
```
client.restart_compute(id = self.result_id),
```
where `self.result_id` is the hash for a particular job. Alternatively, a function instead could change/remove the job status so that it gets rerun automatically.

**Comment by dgasmith** [comment]
Looks good! I think we might do something more like:
```
client.modify_tasks(ids, action)
```

Where action may be `hold`, `restart`, etc. Would this still work for you while allowing more capabilities in the future?

**Comment by jeffschriber** [comment]
I think the `modify_tasks` is a better solution. This could even provide a simple interface to remove queued jobs.
