### ISSUE TITLE
Syntax fix in manager

### ISSUE THREAD

**Issue by jeffschriber** [MolSSI/QCFractal#305]
This is an extremely minor request, but I thought I'd bring it up.

Most options for `qcfractal-manager` look like `--cores-per-worker` and `--memory-per-worker`, where a `-` separates words. To specify tasks per worker, the option is `--tasks_per_worker`, which uses underscores (`_`) unlike all other options. It would be nice to keep consistency and have the option read `--tasks-per-worker`. Feel free to put this at the bottom of any to-do list.

**Comment by Lnaden** [comment]
It was suppose to be that way, mistake from me of copy pasting. I can fix that real quick
