### ISSUE TITLE
Datasets for Grid Optimizations

### ISSUE THREAD

**Issue by jmaat** [MolSSI/QCFractal#308]
I'd like to request adding a feature for grid optimization calculations in labeled datasets.

**Comment by dgasmith** [comment]
Sure, I can get to that. Are there features above the torsiondrive datasets that you would like? For example, what kind of visualization and data organization would you want after the computations complete?

We can also revisit the topic after we have been using the data for a bit.

**Comment by jmaat** [comment]
To clarify I am interested in creating datasets for **grid optimizations**, and not torsion drive datasets. From my understanding the grid optimizations are user specified steps in an angle restraint and torsion drives are full 360 angle scans.  

It would be useful to have the two following features for data processing - 
(a) A combined .xyz coordinate file of all geometries in the grid optimization scan. For example if I performed a grid optimization for the improper angles 20, 0.0, and -20 , the .xyz file would contain three final geometries for each of those steps. 

Having this .xyz file would make it easy to load the geometries from the optimizations into other visualization packages.

(b) I'm also interested in recording wiberg bond order (WBO) and atom connectivity. I am planning on involving trivalent atom centers in the scans I am performing. I want to be able to determine the (a) type of atom attached to the trivalent center and (b) the WBO between the attached atom and the trivalent atom center. 

I am including a example of what this might look like. The "element" # in the image was arbitrarily chosen. 
<img width="344" alt="Screen Shot 2019-06-28 at 1 08 06 PM" src="https://user-images.githubusercontent.com/30784850/60368556-0b04de00-99a6-11e9-97a7-0937e8004ccb.png">

**Comment by dgasmith** [comment]
Right, just curious if you had found TorsionDriveDataset features useful and which ones you would like to retain.

I think we can arrange the `.xyz` writer as well, should be straightforward. WBO is built-in so shouldn't be an issue. Thank you for the graphic- would it be interesting to automatically display WBO on a Molecule in a Jupyter notebook?

**Comment by jmaat** [comment]
I am not familiar with the TorsionDriveDataset features. I think displaying the graphic of the WBO would be an interesting feature!
