### ISSUE TITLE
PostgresHarness startup without PostgreSQL

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#309]
Currently if PostgresHarness attempts to boot without PostgreSQL available in the path a very strange error message occurs. This should explicitly raise an error and 

Likely solution

```python
if shutil.which("pg_ctl") is None:
    raise ValueError("Could not find PostgreSQL. Please `conda install postgresql`.")
```

**Comment by doaa-altarawy** [comment]
Note that in Ubuntu, and by default, `pg_ctl` is `command not found` even when Postgres is installed.
See this [https://dba.stackexchange.com/questions/156717/command-not-found-pg-ctl-on-ubuntu](https://dba.stackexchange.com/questions/156717/command-not-found-pg-ctl-on-ubuntu)

**Comment by dgasmith** [comment]
Interesting, it seems that conda install postgresql explicitly adds it and works fine on all Ubuntu boxes. Also for PostgreSQL 10/11 it seems that it might be more recommended to use.
