### ISSUE TITLE
Accessing intermediate geometries from an optimization

### ISSUE THREAD

**Issue by trevorgokey** [MolSSI/QCFractal#315]
From https://openforcefieldgroup.slack.com/archives/CJQ4DCWN8/p1562092878115000
> I haven't found a better way to get the intermediate geometries from a torsiondrive. I noticed there is `get_trajectory()` to get any intermediate grad step easily, but nothing to get the corresponding molecules for the xyz data. So, right now I am grabbing the molecule ID from each `ResultRecord` individually...

So something fast like `get_trajectory()`, but returns `QCMolecules` instead.

**Comment by dgasmith** [comment]
What about `get_molecular_trajectory`? If I give you the code bits and place could you make a PR?

**Comment by trevorgokey** [comment]
Sure, that works.

**Comment by dgasmith** [comment]
```python
def get_molecular_trajectory():

     mol_ids = [x.molecule for x in  self.get_trajectory()]

     mols = self.client.query_molecules(id=mol_ids)
     mapper = {x.id: x for x in mols}

     return [mapper[x] for x in mol_ids]

```

Somewhere around [here](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/models/records.py#L370). There is local caching tech that you should probably use as well.
