### ISSUE TITLE
Sync Dataset and ProcedureDataset derived data holders

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#343]
ProcedureDataset-based collections have additional features such as `get_entry` and `get_record` that Dataset-based collections do not have. At first pass we can simply add them to Dataset derivatives, but it might be worth taking a deeper look at how the class structures are evolving to make sure the drift isn't too severe.

See https://github.com/openforcefield/qca-dataset-submission/pull/36.

**Comment by dgasmith** [comment]
@mattwelborn Could you consider this issue as well as our overhaul Dataset classes?

**Comment by mattwelborn** [comment]
Can do.
