### ISSUE TITLE
Portal version mismatch error message

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#344]
Error message for portal version mismatch is `	- conda install -c conda-forge qcportal==[0, 8].*` which is not valid bash. Likely should make this a valid bash string so that folks can copy/paste.

**Comment by Lnaden** [comment]
I thought I had already fixed that, and I did for the other version check. 

https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/client.py#L121-L123

Missed the one above it.

**Comment by dgasmith** [comment]
Fixed in #345.
