### ISSUE TITLE
QCFractal Intro Docs

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#346]
Several users have mentioned that one of the issues starting Fractal is trying to understand where everything should live. Should the server be on a laptop or on the supercomputer, or should the manager be on a worker node. This kind of overview information is critical to provide before the Setup Compute/ Setup Server data.

Other minor issues:
 - Current manager examples also require `dtd3` which is not currently in the installs.
 - Discussing what pieces need to be installed where (e.g. does Psi4 need to be installed on the server).

**Comment by dgasmith** [comment]
@mattwelborn the issue related to the intro docs.

**Comment by mattwelborn** [comment]
Closed by PR #362.
