### ISSUE TITLE
Optimization Intermediate Skip

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#347]
There are cases where the individual results of a trajectory in an Optimization is not required or useful and can significantly bulk the data. An example is our current Metabolite set computed with PM6 where the intermediates are not likely worth storing as they make the total optimization ~1000 times larger and can be recomputed not the fly quickly. We should add a `no_intermediates` option to Optimizations to skip storing these intermediates.

**Comment by dgasmith** [comment]
Thinking on this we might have a field like `fractal_options` or similar on record options where we could store this metadata that does not pertain to the computation, but to Fractal specific quantities.

**Comment by dgasmith** [comment]
Thinking on this a bit more. I like the idea of adding this to all procedure records. We can implement the following:

```
class TrajProtocols(Enum, str):
    keep_all = "keep_all"
    keep_initial_and_final = "keep_initial_and_final"
    keep_final = "keep_final"
    keep_none = "keep_none"

class OptimizationProtocol(BaseModel):
    trajectory: TrajProtocols = TrajProtocols.keep_all

class OptimizationRecord(BaseModel):
    protocol: OptimizationProtocal
```

This would be fairly extensible and would help keep options that control storage from computational details.

**Comment by mattwelborn** [comment]
@dgasmith ping. We should make a decision on this quickly if we want to get it into 0.9.0.

**Comment by dgasmith** [comment]
I want to get this in (on the 0.9 milestone). Anyone else have comments on the nomenclature here? @Lnaden

**Comment by Lnaden** [comment]
I like the idea of having this as a Protocol, but I would say for completeness and clarity, call the classes and options more like:

```
class TrajKeepProtocols(Enum, str):
    all = "all"
    endpoints = "endpoints" # or initial_and_final
    final = "final"
    none = "none"

class OptimizationProtocol(BaseModel):
    trajectory_keep_protocol: TrajKeepProtocols = TrajProtocols.all

class OptimizationRecord(BaseModel):
    protocol: OptimizationProtocal
```

so that way its very clear what the option is doing and avoids carrying around `keep_` on each of the settings. We could also leave the shorter names and just have descriptions.

**Comment by dgasmith** [comment]
Looping in @loriab, @muammar, and @j-wags here as well.

**Comment by dgasmith** [comment]
This was added in #421
