### ISSUE TITLE
Documentation: header/banner rendering issue

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#350]
**Describe the bug**
The QCArchive navigation header has numerous display issues, shown below.

http://docs.qcarchive.molssi.org/en/latest/basic_examples/getting_started.html
The banner background is transparent.
<img width="1125" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/1508995/62548094-43fd6180-b834-11e9-88b5-cfbc548a7733.png">

http://docs.qcarchive.molssi.org/en/latest/index.html
The banner includes characters which do not render correctly in Firefox (they render as squares in Chrome).
<img width="1125" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/1508995/62548129-4cee3300-b834-11e9-9799-8b64e81bfbd3.png">

http://docs.qcarchive.molssi.org/projects/qcfractal/en/latest/
The right column of the banner is divided into a white and a gray section.
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/1508995/62548463-d69e0080-b834-11e9-8f02-2ef73ee70271.png">

**To Reproduce**
These issues are most severe on Firefox 68.0.1, macOS 10.14.4, but also noticeable in Chrome 75.0.3770.142.

**Expected behavior**
All characters in the banner should display on modern browsers. The banner background should be white rather than transparent across the entire top of the screen. 

**Additional context**
I think http://docs.qcarchive.molssi.org/en/latest/index.html is rendered from rst and http://docs.qcarchive.molssi.org/en/latest/basic_examples/getting_started.html is rendered from ipynb, which may explain their different display issues.

**Comment by dgasmith** [comment]
The first one is new, might be related to some changing JS issues. The second is known, though I had thought some changes to the backend CSS would have fixed it.

The third is odd, we had fixed this at one point. Let me check into the CSS again.

**Comment by dgasmith** [comment]
I believe these issues are now fixed. Please review them.

**Comment by dgasmith** [comment]
Or maybe not, some sort of CSS deployment bug.

**Comment by dgasmith** [comment]
Alright... I think I have it, Sphinx decided to ignore my CSS add order for whatever reason.

**Comment by mattwelborn** [comment]
Looks great to me. Thanks for taking the time to fix it.
