### ISSUE TITLE
Snowflake pytest failures

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [MolSSI/QCFractal#369]
**Describe the bug**
Tests failing with snowflake, when QCFractal is cloned through github for `test_snowflakehandler_log` and `test_snowflakehandler_restart`

> E           ConnectionRefusedError: [Errno Snowflake instance did not boot properly, try increasing the timeout.
E           
E           stdout:
E           Starting a QCFractal server.
E           
E           QCFractal server base folder: /var/folders/zt/5zfp49y11t585by2_386wfqjz8qxtr/T/tmpkmaaqbdv
E           
E           >>> Examining SSL Certificates...
E           
E           Autogenerated SSL certificates, clients must use 'verify=False' when connecting.
E           
E           >>> Checking the PostgreSQL connection...
E           
E           >>> Initializing the QCFractal server...
E           Fatal during server startup:
E           
E           [Errno 8] nodename nor servname provided, or not known
E           
E           Failed to start the server, shutting down.
E           
E           
E           ] stderr:

qcfractal/snowflake.py:341: ConnectionRefusedError

**To Reproduce**
Following the instructions on the QCFractal docs:

`git clone https://github.com/molssi/qcfractal.git
cd qcfractal
python setup.py install
pytest`

**Comment by mattwelborn** [comment]
This is fixed as of v0.10.0. Please reopen if the problem persists.
