### ISSUE TITLE
pytest failure in qcfractal

### ISSUE THREAD

**Issue by SinaMostafanejad** [MolSSI/QCFractal#370]
**Describe the bug**
A test fails if you clone the github repo and run the pytest.

**To Reproduce**
pytest

**Expected behavior**
Passing  all tests. In this case, 106 skipped, 167 passed and 1 failed.

**Additional context**
A couple initial lines from the error message lines

    def test_snowflakehandler_log():
    
>       with FractalSnowflakeHandler() as server:

qcfractal/tests/test_server.py:136: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
qcfractal/snowflake.py:213: in __init__
    self.start()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by SinaMostafanejad** [comment]
The documentation also does not provide a clear path to see whether or not one has to clone the github repository to be able to run the tests. Also, how we should test qcfractal if we install it using conda.

**Comment by dgasmith** [comment]
Thank you for the example. I agree the documentation on testing is not clear enough for the steps involved. We will work on improving the clarity here.

**Comment by mattwelborn** [comment]
This is fixed as of v0.10.0. Please reopen if the problem persists.
