### ISSUE TITLE
QCFractal Quickstart Tutorial Error

### ISSUE THREAD

**Issue by sgreene8** [MolSSI/QCFractal#371]
I ran the Quickstart Tutorial [here](http://docs.qcarchive.molssi.org/projects/qcfractal/en/latest/quickstart.html), executing a geometry optimization on H2O as specified in the tutorial. The optimization failed with the following error:
geomeTRIC run_json error:
Traceback (most recent call last):
  File "//anaconda3/envs/snowflake/lib/python3.7/site-packages/geometric/run_json.py", line 214, in geometric_run_json
    geometric.optimize.Optimize(coords, M, IC, engine, None, params)
  File "//anaconda3/envs/snowflake/lib/python3.7/site-packages/geometric/optimize.py", line 1331, in Optimize
    return optimizer.optimizeGeometry()
  File "//anaconda3/envs/snowflake/lib/python3.7/site-packages/geometric/optimize.py", line 1293, in optimizeGeometry
    self.calcEnergyForce()
  File "//anaconda3/envs/snowflake/lib/python3.7/site-packages/geometric/optimize.py", line 1002, in calcEnergyForce
    spcalc = self.engine.calc(self.X, self.dirname)
  File "//anaconda3/envs/snowflake/lib/python3.7/site-packages/geometric/engine.py", line 873, in calc
    return self.calc_new(coords, dirname)
  File "//anaconda3/envs/snowflake/lib/python3.7/site-packages/geometric/engine.py", line 865, in calc_new
    raise QCEngineAPIEngineError("QCEngineAPI computation did not execute correctly. Message: " + ret["error"]["error_message"])
geometric.errors.QCEngineAPIEngineError: QCEngineAPI computation did not execute correctly. Message: QCEngine Unknown Error: Traceback (most recent call last):
  File "//anaconda3/envs/snowflake/bin/psi4", line 250, in <module>
    os.unlink(args["output"])
FileNotFoundError: [Errno 2] No such file or directory: 'data.json.dat'

To my knowledge, I had not previously installed psi4 on my computer.

**Comment by dgasmith** [comment]
Can you run a `conda list` I would guess that this is an old version issue.

**Comment by sgreene8** [comment]
Do you just want the output of `conda list`?

# packages in environment at //anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
alembic                   1.0.11                     py_0    conda-forge
anaconda                  2019.07                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_0  
anaconda-project          0.8.3                      py_0  
appnope                   0.1.0                    py37_0  
appscript                 1.1.0            py37h1de35cc_0  
arrow                     0.14.5                   py37_0    conda-forge
asn1crypto                0.24.0                   py37_0  
astroid                   2.2.5                    py37_0  
astropy                   3.2.1            py37h1de35cc_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
babel                     2.7.0                      py_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.5                        py_2  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
backports.tempfile        1.0                        py_1  
backports.weakref         1.0.post1                  py_1  
bcrypt                    3.1.6            py37h01d97ff_1    conda-forge
beautifulsoup4            4.7.1                    py37_1  
binaryornot               0.4.4                      py_1    conda-forge
biopython                 1.74             py37h01d97ff_0    conda-forge
bitarray                  0.9.3            py37h1de35cc_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
blosc                     1.16.3               hd9629dc_0  
bokeh                     1.2.0                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h1d22016_1  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py37_0    conda-forge
cffi                      1.12.3           py37hb5b8e2f_0  
cftime                    1.0.3.4         py37h1e5eb4f_1001    conda-forge
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
cloudpickle               1.2.1                      py_0  
clyent                    1.2.2                    py37_1  
cmake                     3.14.0               haff7e42_0  
colorama                  0.4.1                    py37_0  
conda                     4.7.11                   py37_0    conda-forge
conda-build               3.18.8                   py37_0  
conda-env                 2.6.0                         1  
conda-package-handling    1.3.11                   py37_0  
conda-verify              3.4.2                      py_1  
contextlib2               0.5.5                    py37_0  
cookiecutter              1.6.0                 py37_1000    conda-forge
cryptography              2.7              py37ha12b0ac_0  
curl                      7.65.2               ha441bb4_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.12          py37h0a44026_0  
cytoolz                   0.10.0           py37h1de35cc_0  
dask                      2.1.0                      py_0  
dask-core                 2.1.0                      py_0  
dbus                      1.13.6               h90a0687_0  
decorator                 4.4.0                    py37_1  
defusedxml                0.6.0                      py_0  
dftd3                     3.2.1                h0e1e685_0    psi4
distributed               2.1.0                      py_0  
docutils                  0.14                     py37_0  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.1.0            py37h1de35cc_0  
filelock                  3.0.12                     py_0  
flask                     1.1.1                      py_0  
freetype                  2.9.1                hb4e5f40_0  
future                    0.17.1                   py37_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.4.0            py37h1de35cc_0  
glib                      2.56.2               hd9629dc_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
greenlet                  0.4.15           py37h1de35cc_0  
griddataformats           0.5.0                      py_0    conda-forge
gsd                       1.8.0            py37heacc8b8_1    conda-forge
h5py                      2.9.0            py37h3134771_0  
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.4               hfa1e0ec_0  
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
imageio                   2.5.0                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.17                     py37_1  
intel-openmp              2019.4                      233  
ipykernel                 5.1.1            py37h39e3cac_0  
ipython                   7.6.1            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.0                      py_0  
isort                     4.3.21                   py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4.1                      py_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10.1                   py37_0  
jinja2-time               0.2.0                      py_2    conda-forge
joblib                    0.13.2                   py37_0  
jpeg                      9b                   he5867d9_2  
json5                     0.8.4                      py_0  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.1                      py_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.5.0                      py_0  
jupyterlab                1.0.2            py37hf63ae98_0  
jupyterlab_server         1.0.0                      py_0  
keyring                   18.0.0                   py37_0  
kiwisolver                1.1.0            py37h0a44026_0  
krb5                      1.16.1               hddcf347_7  
lazy-object-proxy         1.4.1            py37h1de35cc_0  
libarchive                3.3.3                h786848e_5  
libcurl                   7.65.2               h051b688_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
liblief                   0.9.0                h2a1bed3_2  
libnetcdf                 4.6.1                hd5207e6_2  
libpng                    1.6.37               ha441bb4_0  
libpq                     11.2                 h051b688_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.2                ha12b0ac_0  
libtiff                   4.0.10               hcb84e12_2  
libxml2                   2.9.9                hf6e021a_1  
libxslt                   1.1.33               h33a18ac_0  
llvm-openmp               4.0.1                hcfea43d_1  
llvmlite                  0.29.0           py37h98b8051_0  
locket                    0.2.0                    py37_1  
lxml                      4.3.4            py37hef8c89e_0  
lz4-c                     1.8.1.2              h1de35cc_0  
lzo                       2.10                 h362108e_2  
mako                      1.1.0                      py_0    conda-forge
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.1.0            py37h54f8f79_0  
mccabe                    0.6.1                    py37_1  
mdanalysis                0.19.2          py37h0a44026_1000    conda-forge
mdtraj                    1.9.3            py37h5a8e3e4_0    conda-forge
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.0.2            py37h1de35cc_0  
mkl_fft                   1.0.12           py37h5e564d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
mmtf-python               1.1.2                      py_0    conda-forge
mock                      3.0.5                    py37_0  
more-itertools            7.0.0                    py37_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.6.1            py37h04f5b5a_1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
netcdf4                   1.4.2            py37h13743db_0  
networkx                  2.3                        py_0  
nltk                      3.4.4                    py37_0  
nose                      1.3.7                    py37_2  
notebook                  6.0.0                    py37_0  
numba                     0.44.1           py37h6440ff4_0  
numexpr                   2.6.9            py37h7413580_0  
numpy                     1.16.4           py37hacdab7b_0  
numpy-base                1.16.4           py37h6575580_0  
numpydoc                  0.9.1                      py_0  
olefile                   0.46                     py37_0  
openpyxl                  2.6.2                      py_0  
openssl                   1.1.1c               h1de35cc_1  
packaging                 19.0                     py37_0  
pandas                    0.24.2           py37h0a44026_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.5.0                      py_0  
partd                     1.0.0                      py_0  
path.py                   12.0.1                     py_0  
pathlib2                  2.3.4                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 h0a44026_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.1.0            py37hb68e598_0  
pint                      0.9                      py37_2    conda-forge
pip                       19.1.1                   py37_0  
pkginfo                   1.5.0.1                  py37_0  
pluggy                    0.12.0                     py_0  
ply                       3.11                     py37_0  
postgresql                11.2                 h051b688_0  
poyo                      0.5.0                      py_0    conda-forge
prometheus_client         0.7.1                      py_0  
prompt_toolkit            2.0.9                    py37_0  
psutil                    5.6.3            py37h1de35cc_0  
psycopg2                  2.8.2            py37h212c5bf_0    conda-forge
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    py37_0  
py-cpuinfo                5.0.0                      py_0    conda-forge
py-lief                   0.9.0            py37h1413db1_2  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h1de35cc_9  
pycurl                    7.43.0.3         py37ha12b0ac_0  
pydantic                  0.32.1           py37h01d97ff_0    conda-forge
pyflakes                  2.1.1                    py37_0  
pygments                  2.4.2                      py_0  
pylint                    2.3.1                    py37_0  
pyodbc                    4.0.26           py37h0a44026_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.14.11          py37h1de35cc_0  
pysocks                   1.7.0                    py37_0  
pytables                  3.5.2            py37h5bccee9_1  
pytest                    5.0.1                    py37_0    conda-forge
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.3.0                    py37_0  
pytest-openfiles          0.3.2                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.3                h359304d_0  
python-dateutil           2.8.0                    py37_0  
python-editor             1.0.4                      py_0    conda-forge
python-libarchive-c       2.8                     py37_11  
python.app                2                        py37_9  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py37h1d22016_1  
pyyaml                    5.1.1            py37h1de35cc_0  
pyzmq                     18.0.0           py37h0a44026_0  
qcelemental               0.6.0                      py_0    conda-forge
qcengine                  0.9.0                      py_0    conda-forge
qcfractal                 0.8.0                      py_0    conda-forge
qt                        5.9.7                h468cd18_1  
qtawesome                 0.5.7                    py37_1  
qtconsole                 4.5.1                      py_0  
qtpy                      1.8.0                      py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.22.0                   py37_0  
rhash                     1.3.8                ha12b0ac_0  
rope                      0.14.0                     py_0  
ruamel_yaml               0.15.46          py37h1de35cc_0  
scikit-image              0.15.0           py37h0a44026_0  
scikit-learn              0.21.2           py37h27c97d8_0  
scipy                     1.3.0            py37h1410ff5_0  
seaborn                   0.9.0                    py37_0  
send2trash                1.5.0                    py37_0  
setuptools                41.0.1                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.9.0                      py_0  
sortedcollections         1.1.2                    py37_0  
sortedcontainers          2.1.0                    py37_0  
soupsieve                 1.8                      py37_0  
sphinx                    2.1.2                      py_0  
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.1                      py_0  
sphinxcontrib-devhelp     1.0.1                      py_0  
sphinxcontrib-htmlhelp    1.0.2                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.2                      py_0  
sphinxcontrib-serializinghtml 1.1.3                      py_0  
sphinxcontrib-websupport  1.1.2                      py_0  
spyder                    3.3.6                    py37_0  
spyder-kernels            0.5.1                    py37_0  
sqlalchemy                1.3.5            py37h1de35cc_0  
sqlite                    3.29.0               ha441bb4_0  
statsmodels               0.10.0           py37h1d22016_0  
sympy                     1.4                      py37_0  
tbb                       2019.7               h770b8ee_0    conda-forge
tblib                     1.4.0                      py_0  
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.3            py37h1de35cc_0  
tqdm                      4.32.1                     py_0  
traitlets                 4.3.2                    py37_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.24.2                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py37_0  
whichcraft                0.6.0                      py_0    conda-forge
widgetsnbextension        3.5.0                    py37_0  
wrapt                     1.11.2           py37h1de35cc_0  
wurlitzer                 1.0.2                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.8                      py_0  
xlwings                   0.15.8                   py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
yapf                      0.28.0                     py_0    conda-forge
zeromq                    4.3.1                h0a44026_3  
zict                      1.0.0                      py_0  
zipp                      0.5.1                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by dgasmith** [comment]
This may not be the correct environment as it does not show Psi4 installed.

**Comment by sgreene8** [comment]
Ah, yes. Here is the correct environment:
# packages in environment at //anaconda3/envs/snowflake:
#
# Name                    Version                   Build  Channel
ambit                     0.3                  h57cbb5c_0    psi4
appnope                   0.1.0                    py37_0  
asn1crypto                0.24.0                   py37_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
backcall                  0.1.0                    py37_0  
bcrypt                    3.1.6            py37h1de35cc_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
boost                     1.70.0           py37haf112f3_1    conda-forge
boost-cpp                 1.70.0               hd59e818_1    conda-forge
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2019.5.15                     1  
cairo                     1.16.0            h0ab9d94_1001    conda-forge
certifi                   2019.6.16                py37_1  
cffi                      1.12.3           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
chemps2                   1.8.9                h57cbb5c_0    psi4
cryptography              2.7              py37ha12b0ac_0  
decorator                 4.4.0                    py37_1  
deepdiff                  4.0.7                      py_0    conda-forge
defusedxml                0.6.0                      py_0  
dkh                       1.2                  ha0829f0_3    psi4
entrypoints               0.3                      py37_0  
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.9.1                hb4e5f40_0  
gau2grid                  1.3.1                h1d22016_0    psi4
gdma                      2.2.6                hdc02c5d_5    psi4
geometric                 0.9.7.2                    py_0    conda-forge
gettext                   0.19.8.1             h15daf44_3  
glib                      2.58.3            h9d45998_1002    conda-forge
hdf5                      1.10.2               hfa1e0ec_1  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
importlib_metadata        0.19                     py37_0  
intel-openmp              2019.4                      233  
ipykernel                 5.1.1            py37h39e3cac_0  
ipython                   7.7.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10.1                   py37_0  
jpeg                      9b                   he5867d9_2  
jsonpickle                1.2                        py_0  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.1                      py_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.5.0                      py_0  
krb5                      1.16.1               hddcf347_7  
libcurl                   7.65.2               h051b688_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libint                    1.2.1                h1989688_2    psi4
libpng                    1.6.37               ha441bb4_0  
libpq                     11.2                 h051b688_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.2                ha12b0ac_0  
libtiff                   4.0.10               hcb84e12_2  
libxc                     4.3.4                h1de35cc_0    psi4
libxml2                   2.9.9                hf6e021a_1  
markupsafe                1.1.1            py37h1de35cc_0  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl_fft                   1.0.12           py37h5e564d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
mongodb                   4.0.3                hccea1a4_0  
mongoengine               0.18.2                   py37_0    conda-forge
more-itertools            7.2.0                    py37_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.3                        py_0  
notebook                  6.0.0                    py37_0  
numpy                     1.16.4           py37hacdab7b_0  
numpy-base                1.16.4           py37h6575580_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1c               h1de35cc_1  
ordered-set               3.1.1                      py_0    conda-forge
packaging                 19.0                     py37_0  
pandas                    0.25.0           py37h0a44026_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.5.0                      py_0  
pcmsolver                 1.2.1            py37h92ea98a_0    psi4
pcre                      8.43                 h0a44026_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.1.0            py37hb68e598_0  
pint                      0.9                      py37_2    conda-forge
pip                       19.1.1                   py37_0  
pixman                    0.38.0               h1de35cc_0  
plotly                    4.0.0                      py_0  
pluggy                    0.12.0                     py_0  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            2.0.9                    py37_0  
psi4                      1.3.2+ecbda83    py37h7101e00_0    psi4
psutil                    5.6.3            py37h1de35cc_0  
psycopg2                  2.7.6.1          py37ha12b0ac_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    py37_0  
py-cpuinfo                5.0.0                      py_0  
py3dmol                   0.8.0                      py_0    conda-forge
pycairo                   1.18.1           py37ha54c0a8_0  
pycparser                 2.19                     py37_0  
pydantic                  0.32.1           py37h01d97ff_0    conda-forge
pygments                  2.4.2                      py_0  
pymongo                   3.8.0            py37h0a44026_1  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.6.0            py37h655552a_6  
pyrsistent                0.14.11          py37h1de35cc_0  
pysocks                   1.7.0                    py37_0  
pytest                    5.0.1                    py37_0  
python                    3.7.4                h359304d_1  
python-dateutil           2.8.0                    py37_0  
pytz                      2019.1                     py_0  
pyyaml                    5.1.1            py37h1de35cc_0  
pyzmq                     18.0.0           py37h0a44026_0  
qcelemental               0.4.2                      py_0    conda-forge
qcengine                  0.8.2                      py_0    conda-forge
qcfractal                 0.7.2                      py_0    conda-forge
qcportal                  0.7.2                      py_0    conda-forge
qt                        5.6.3                h1d42b2f_0  
qtconsole                 4.5.2                      py_0  
rdkit                     2019.03.4        py37hbdb07b7_0    conda-forge
readline                  7.0                  h1de35cc_5  
requests                  2.22.0                   py37_0  
retrying                  1.3.3                    py37_2  
send2trash                1.5.0                    py37_0  
setuptools                41.0.1                   py37_0  
simint                    0.7                  h9ec563c_2    psi4
sip                       4.18.1           py37h0a44026_2  
six                       1.12.0                   py37_0  
sqlalchemy                1.3.5            py37h1de35cc_0  
sqlite                    3.29.0               ha441bb4_0  
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.3            py37h1de35cc_0  
traitlets                 4.3.2                    py37_0  
urllib3                   1.24.2                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.33.4                   py37_0  
widgetsnbextension        3.5.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.3.1                h0a44026_3  
zipp                      0.5.2                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by dgasmith** [comment]
That looks right and I do not see an obvious issues (BTW you can use three backpacks to format blocks like the above). Let me check into a few things and I should have another environment for you to try.

**Comment by mattwelborn** [comment]
@sgreene8 This was an issue with the qcf-snowflake enviornment and has been fixed. I'm going to close the issue; feel free to reopen it if your problem persists.
