### ISSUE TITLE
QCPortal: list methodologies in Dataset and ReactionDataset

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#379]
**Is your feature request related to a problem? Please describe.**
In Dataset and ReactionDataset, it can be difficult to ascertain what data are available.

**Describe the solution you'd like**
A function which returns unique (method, basis set) pairs.

**Describe alternatives you've considered**
`ds.list_history().reset_index().groupby(['method','basis']).size().reset_index()`

**Additional context**
@dgasmith please @ me on the PR so I can see how this works.

**Comment by dgasmith** [comment]
What about something like:
```
ds.list_history(counts=('method', 'basis'))
```

Or similar which would basically run the query your describe above?

**Comment by mattwelborn** [comment]
This is pretty much resolved by the QCA cookbook.
