### ISSUE TITLE
Dataset Row Names

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#381]
At one point I made an attempt to rename the rows of a collection (either Dataset, or Procedure Dataset) to "Entry" or similar so that we can keep the name "Records" specifically to the ResultRecords, OptimizationRecords, etc. I didn't change this in Dataset as there was an upcoming conflict at the time.

So now in ProcedureDatasets we have "Entry" as the row class type while in Dataset we have "Records" as the row class type. I think we need to make this consistent before we release another version. Anyone have thoughts on the name of an "Entry"?
 
@doaa-altarawy @mattwelborn

**Comment by mattwelborn** [comment]
PR #384

**Comment by mattwelborn** [comment]
After the QCA migration to v0.10.0, this is done, right?

**Comment by dgasmith** [comment]
Yup!
