### ISSUE TITLE
Projecting a torsiondrive with optimization_history fails.

### ISSUE THREAD

**Issue by trevorgokey** [MolSSI/QCFractal#383]
**Describe the bug**
I get an error if I try to use `projection={'optimization_history': True}` on a torsiondrive.

**To Reproduce**
Code to reproduce the behavior:
```
In [348]: client.query_procedures(id='1762049', procedure='torsiondrive', projection={'optimization_history' : True }, full_return=True).dict()  
Out[348]: 
{'meta': {'errors': [],
  'success': False,
  'error_description': "SQL expression, column, or mapped entity expected - got '{}'",
  'missing': [],
  'n_found': 0},
 'data': []}
```

**Expected behavior**
Should get the corresponding dictionary.

**Additional context**
#380 and #382 possibly related. `projection={'final_energy_dict': True} works.

**Comment by doaa-altarawy** [comment]
Thanks for reporting this, I'm looking into it.

**Comment by doaa-altarawy** [comment]
Should be fixed now with the new include/exclude PRs
