### ISSUE TITLE
Release Linting

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#386]
Before 0.10.0 is released we should YAPF, isort, Codecov check, and LGTM check the entire code base. Development should be at a low point and everything merged.

**Comment by mattwelborn** [comment]
Let's also check that #369 and #370 are fixed before we release.

**Comment by mattwelborn** [comment]
v0.10.0 has come and gone.

**Comment by dgasmith** [comment]
We didn't do this. Let me tackle it.
