### ISSUE TITLE
Results stuck in INCOMPLETE state after parsl failure

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#391]
**Describe the bug**
Results can become stuck in an `INCOMPLETE` state after a parsl manager fails to handle them. The parsl manager failure is an upstream bug, but it has exposed this issue. In this parsl issue, the manager starts to work on a result and then holds onto it indefinitely. After this point, it is impossible to get a result for this calculation. It cannot be resubmitted or wrested from the manager. There should be a mechanism for automatically re-queuing such jobs after a timeout or at least the ability to manually re-queue them.

**To Reproduce**
A Result with this issue can be found on the QCArchive:
```
import qcportal as ptl
client = ptl.FractalClient()
client.query_results(id='4312483')[0].dict()
```
Output:
```
{'id': '4312483',
 'hash_index': None,
 'procedure': 'single',
 'program': 'psi4',
 'version': 1,
 'extras': {},
 'stdout': None,
 'stderr': None,
 'error': None,
 'task_id': None,
 'manager_name': None,
 'status': <RecordStatusEnum.incomplete: 'INCOMPLETE'>,
 'modified_on': datetime.datetime(2019, 8, 26, 21, 11, 44, 363961),
 'created_on': datetime.datetime(2019, 8, 26, 21, 11, 44, 363964),
 'provenance': None,
 'driver': <DriverEnum.energy: 'energy'>,
 'method': 'pbe',
 'molecule': '3592424',
 'basis': '6-31g',
 'keywords': None,
 'return_result': None,
 'properties': None}
```

**Expected behavior**
This calculation should be picked up by another manager automatically. Or, it should be possible to re-queue it using `client.modify_tasks`. (`client.modify_tasks("restart")` only works on `ERROR` state Results and does nothing to `INCOMPLETE` ones.)

**Additional context**
The upstream parsl issue will be linked here once it has been reported.

**Comment by dgasmith** [comment]
Confirmed #388 fixes this.
