### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by jchodera** [MolSSI/QCFractal#398]
Are there standard API docs for QCFractal on readthedocs somewhere? The [online documentation](https://docs.qcarchive.molssi.org/en/latest/basic_examples/QCFractal.html) has some really nice "module demos" docs, but no browsable API docs that I can find. 

These should be simple to set up with [Sphinx's auto API docs features](https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html) and highly useful.

**Comment by dgasmith** [comment]
Which docs are you looking for? Full portal docs API can be found [here](http://docs.qcarchive.molssi.org/projects/QCPortal/en/stable/client-api.html) for example.

**Comment by dgasmith** [comment]
The documentation dropdown was the supposed path. Underneath project demo's on the index page we should add a link to the documentation pages and at the beginning/end of the project demo's we should also link to the respect documentation pages.

**Comment by mattwelborn** [comment]
Thanks for the feedback! This has been addressed in MolSSI/QCArchiveInfrastructureWebsite#3.
