### ISSUE TITLE
OptimizationDataset example?

### ISSUE THREAD

**Issue by jchodera** [MolSSI/QCFractal#412]
**Is your feature request related to a problem? Please describe.**
The current [examples page](https://qcarchive.molssi.org/examples/) features several excellent Jupyter notebook tutorials for various datasets, but lacks an example for `OptimizationDataset`.

**Describe the solution you'd like**
It would be very useful to have a similar tutorial for `OptimizationDataset`; ideally one which demonstrates how to also extract the minimization trajectories to illustrate how to use energies and gradients collected from these trajectories.

**Describe alternatives you've considered**
It was difficult to reconstruct how to query `OptimizationDataset` by analogy from the `ReactionDataset` and `TorsionDriveDataset` examples.

**Additional context**
![image](https://user-images.githubusercontent.com/3656088/65730600-3fc62580-e0ba-11e9-889d-d7c442adb189.png)

**Comment by mattwelborn** [comment]
Thanks for this report. I’m planning to work on documentation next week now that #411 is merged, and I’ll address this.

**Comment by jchodera** [comment]
Thanks! @yuanqing-wang may have additional feedback on things that would be useful to see in the example.
