### ISSUE TITLE
Grid Optimization Datasets: Add Pre-optimization IDs

### ISSUE THREAD

**Issue by jmaat** [MolSSI/QCFractal#413]
**Is your feature request related to a problem? Please describe.**
I want to be able to access pre-optimization job ids and related data (energies, geometries, wbo, etc.) for these optimizations. This is the optimization that occurs before the restrained grid optimization calculation takes place. I specifically want this function added to grid optimization datasets.

**Describe the solution you'd like**
Add specific job IDs to the pre-optimization set so they are queryable.

**Comment by dgasmith** [comment]
I think this falls under a bug, we missed this when generating the GridOptimization class. Will try to fix over the next several days.
