### ISSUE TITLE
Molecules in OpenFF Trivalent Nitrogen Set 1 lacking optimization frames

### ISSUE THREAD

**Issue by btjanaka** [MolSSI/QCFractal#435]
**Describe the bug**
In the "GridOptimizationDataset" called "OpenFF Trivalent Nitrogen Set 1", some molecules appear to have no optimizations run on them - i.e. there are no optimization frames available.

**To Reproduce**
```
import numpy as np
import qcportal as ptl
from matplotlib import pyplot as plt
from sklearn import decomposition

CLIENT = ptl.FractalClient()
DATASET = CLIENT.get_collection('GridOptimizationDataset',
                                'OpenFF Trivalent Nitrogen Set 1')
MOLECULE_IDS = [
    DATASET.get_entry(index).initial_molecule for index in DATASET.df.index
]
MOLECULES = CLIENT.query_molecules(id=MOLECULE_IDS)
METADATA_ENTRIES = [
    DATASET.get_entry(index).object_map['default'] for index in DATASET.df.index
]
# get all grid optimization calculations from the entire dataset
ENTRIES = CLIENT.query_procedures(METADATA_ENTRIES)

# Prints out all molecules that are missing optimization frames - we expect 21
for idx, entry in enumerate(ENTRIES):
    final_energies = entry.get_final_energies()
    if len(final_energies) != 21:
        print(f"Molecule {idx:3} ({MOLECULES[idx].get_molecular_formula()}) has {len(final_energies)} frames")
```
The output from this code is:
```
Molecule  66 (C22Cl2H24NO6PS) has 0 frames
Molecule  83 (C16H37NO2P2S2) has 0 frames
Molecule  84 (C22H24NO2PS) has 0 frames
Molecule  85 (C20H21N3O4S) has 0 frames
Molecule 138 (C4H6N2O) has 0 frames
Molecule 141 (C19H13NO3S) has 0 frames
Molecule 157 (C31H45N3O8S3) has 0 frames
Molecule 160 (C21H22N2O6S2) has 0 frames
Molecule 175 (C28H22NO2P) has 0 frames
Molecule 193 (C22H24N6O6S2) has 0 frames
Molecule 204 (C12H21N2P) has 0 frames
Molecule 218 (BrC9H8N3) has 0 frames
Molecule 236 (C6H5N3) has 0 frames
Molecule 242 (C13H18N3O2) has 0 frames
Molecule 252 (C24H20NOP) has 0 frames
Molecule 277 (C12H11N2O3S) has 0 frames
Molecule 279 (C10H8N2O2) has 0 frames
Molecule 286 (C7H4INO3S) has 0 frames
Molecule 298 (C22H30N3P) has 0 frames
```
That means **19 molecules** lack optimizations.

**Expected behavior**
All molecules should have 21 optimization frames, and there should be no output in the code above.

**Additional context**
This dataset was created by Jessica Maat here: https://github.com/openforcefield/qca-dataset-submission/tree/master/2019-06-28-Nitrogen-grid-optimization

**Comment by dgasmith** [comment]
If you check the `DATASET.status()` of these you will see that they are labeled as `INCOMPLETE` meaning that they have not finished yet. In reality these have all failed

In addition, you can also use the `df.query('default')` syntax to skip the `query_procedures` line and have it execute for you automatically. 

The lack of a `FAILURE` message is on us, and something that we will fix this release cycle (early November).

**Comment by dgasmith** [comment]
Partial frames are now updated on the gridoptimization record so even if complete you will see the intermediate frames.
