### ISSUE TITLE
Access log of incomplete calculations

### ISSUE THREAD

**Issue by ChayaSt** [MolSSI/QCFractal#451]
It would be very helpful to have access to the logs of incomplete calculations. This is especially useful for debugging calculations that are taking longer than anticipated.

**Comment by dgasmith** [comment]
This is very specifically for services correct? Can you give an example of your expected usage?

**Comment by ChayaSt** [comment]
Yes - this is for torsion scans. What would be helpful to have is access to is:
1. How many geometry optimizations (or data points on the scan) were already calculated
2. How many iterations for the geometry optimizations
3. How many geometry optimization iterations were complete for the wavefront propagation. 

What I am envisioning is that the 
```
opt = td.get_history(180, minimum=True)
result = opt.get_trajectory()[-1]
```
To work for incomplete scans. It would also be good to have a summary printout of the numbers of optimization and iterations complete 

Bonus feature: 
It would also be helpful to see where the wavefront propagation is up to - [TorsionDrive](https://github.com/lpwgroup/torsiondrive) has visualization of this on the command line for 1D and 2D scans.
