### ISSUE TITLE
Collection Metadata Database Column

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#465]
From #458 we need to add a new database column of `metadata = '{}'::json` and remove the pydantic `Optional` to ease migration and prevent conflicts in the future.

**Comment by dgasmith** [comment]
For #463 `qcfractal/alembic/versions/a2f76bb7be65_updates_collections_table_with_owner_.py` add `op.alter_column('collection', 'group', nullable=False)`.

**Comment by mattwelborn** [comment]
Are you sure the group shouldn't be nullable? It's Optional in our collection datamodel and nullable in the ORM. Also, execute is mispelled in line 22
https://github.com/MolSSI/QCFractal/blob/36352189cb7ec5e91dd8ea15dccf49953d342650/qcfractal/alembic/versions/a2f76bb7be65_updates_collections_table_with_owner_.py#L22

**Comment by dgasmith** [comment]
As record @mattwelborn discussed this and we will make the group non-nullable with the current default.
