### ISSUE TITLE
Query Results without projection

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#478]
**Describe the bug**

Calling query result without a projection creates an internal server error on the main QCArchive server. Server logs show that that the return is invalidated as all fields are None. Since we do have tests for this in the Fractal stack unsure what is going on here. 

**To Reproduce**
Call ‘client.query_results’ without a projection. 

**Expected behavior**

**Additional context**

**Comment by dgasmith** [comment]
Looks like a version error, requiring QCPortal 0.12.1 to match QCFractal 0.12.(>=1).

**Comment by mattwelborn** [comment]
Is this resolved?
