### ISSUE TITLE
REST API for metadata

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#489]
**Is your feature request related to a problem? Please describe.**
When querying large tables like results, molecules, kvs, etc., it can be helpful to get metadata about the response before performing a full query. For example, it could be helpful to know how many results are returned by a query before deciding whether to pull down all of those results.

**Describe the solution you'd like**
A REST endpoint for getting metadata. This would be a subresource. For example, `/molecule` would have a new subresource called `/molecule/metadata`. This subresource would return scalar metadata information such as the total number of matches to a query. 

**Describe alternatives you've considered**
Adding a new field to the existing REST GET model metadata that causes only metadata to be returned in the response's metadata field with no data. This metadata would contain additional scalar metadata information that is not normally computed or returned.

**Comment by dgasmith** [comment]
```
>>> client.query_molecules(full_return=True, limit=1).meta
ResponseGETMeta(errors=[], success=True, error_description='False', missing=[], n_found=9232446)
```

**Comment by dgasmith** [comment]
`limit=0` should be made to work, unsure what's going on there.

**Comment by mattwelborn** [comment]
Let's make limit=0 work and add it to 0.12.2
