### ISSUE TITLE
CLI Database Backup/Restore

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#510]
**Is your feature request related to a problem? Please describe.**
To make it easier to backup and restore the database CLI solutions should be implemented.

**Describe the solution you'd like**
`qcfractal-server backup file.backup` to backup the database. Automatically saving snapshots should be considered, but seems overkill.

`qcfractal-server restore file.backup` to restore from a file. Would require the usual equivalence test of the best folder from the CLI (similar to resetting the folder) in order to overwrite the database.

@doaa-altarawy @mattwelborn What do you think?

**Comment by mattwelborn** [comment]
Much needed feature. Data preservation is a key goal of the project, and we can’t expect folks to pg_dump on their own.

**Comment by doaa-altarawy** [comment]
Yes, this is very important. Restore will work only with the same QCFractal version that it had been backed up with though. This should be clear.
