### ISSUE TITLE
Docker Images and Conda Envs

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#515]
It would be nice to build the docker images from our conda envs and keep them in sync so that the two can be created from either side. Either a airflow or GHA trigger I think?

Bonus for a small part of the docs listing available images.

@jchodera

**Comment by mattwelborn** [comment]
Could you please unpack "created from either side"?

**Comment by dgasmith** [comment]
The conda and Docker images should be as identical as possible. This means that we would be able to create a `qcfractal_oss_worker` environment from a conda environment file uploaded to our QCArchive conda channel (https://anaconda.org/QCArchive) as well as a `qcfractal_oss_worker` Docker image on our MolSSI Docker channel where the Docker image would be created using `conda env qcarchive/qcfractal_oss_worker` so that the two are nearly identical.

**Comment by mattwelborn** [comment]
The conda envs don't include fractal and the Docker images do. Are you envisioning adding four new Docker images corresponding the conda envs without fractal, but tagged corresponding to the Fractal version they came from? On the flip side, there would be two new conda envs corresponding to the Docker images, which contain specific versions of fractal?

**Comment by dgasmith** [comment]
I am thinking of the [prod-envs](https://github.com/MolSSI/QCFractal/blob/master/devtools/prod-envs/qcf-manager-openff.yaml) not the `conda-envs` where we get this folder and the Docker images in sync. The `conda-envs` might need to be renamed `ci-envs` or similar to be a bit more explicit.

Apologies for the confusion there, we have many envs and images running around.

**Comment by jchodera** [comment]
What about the [`qcfractal/qcf-snowflake`](https://anaconda.org/QCArchive/qcf-snowflake/files) environment described in the [QCFractal Quickstart](http://docs.qcarchive.molssi.org/projects/QCFractal/en/stable/quickstart.html) docs? Would be great if this could be kept in sync too, since it's super easy to reproducibly create the correct environment this way.

**Comment by dgasmith** [comment]
Yup, the snowflake environment is part of the `prod-envs` folder. We have all of the pieces in place, the only item that we need is a bit more automation to spawn the updating of these files on conda + Docker rebuild.

I think this is likely a good candidate for some internal Airflow workflows. If it isn't Airflow we would need to spin this off into (yet) another repo that can be spawned via GHA in a sane manner.

**Comment by dgasmith** [comment]
Probably closed by #518. Will close once everything is up.

**Comment by mattwelborn** [comment]
Happiness is a green DAG:
![image](https://user-images.githubusercontent.com/1508995/71131770-a2aff000-21c3-11ea-8970-5df11793d682.png)

**Comment by dgasmith** [comment]
I am glad we have campaign managers to manage our workflows for our campaign managers...

**Comment by Lnaden** [comment]
![image](https://user-images.githubusercontent.com/3809383/71174014-1d175900-2232-11ea-990d-e3531d3cd968.png)
