### ISSUE TITLE
Mutliple tags per manager

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#526]
**Is your feature request related to a problem? Please describe.**
Some managers can only handle certain jobs. Some managers can handle many jobs. To address the former, special tags have to be created. It would be nice if these tags could also be picked up by the latter.

**Describe the solution you'd like**
Managers can accept jobs from multiple different tags, with a priority order.

**Describe alternatives you've considered**
Changing manager tags as campaigns progress. Multiple tags per jobs. 

**Additional context**

**Comment by dgasmith** [comment]
Closed by #541.
