### ISSUE TITLE
ReactionDataset CP DFTD3 energy.

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#527]
**Describe the bug**
Counterpoise correction does not currently work with DFT-D3 in ReactionDatasets as CP/noCP does not make sense for the -D3 term. DFTD3 compute always takes the noCP stoichiometry, but the query planner takes the stoichiometry of the parent. A query for CP DFT-D3 cannot correctly complete, because the monomers will never be available. To fix, the query planner needs the same logic of the compute where DFTD3 is always cast to noCP.

**To Reproduce**
Query a -D3 with CP on any ReactionDataset.

I need to take a deeper look, but I thought the compute and query planners were identical to avoid this exact problem.

**Comment by mattwelborn** [comment]
Suggested solution: Rerun DFTD3 on CP, since it costs few CPU hours and the storage costs are manageable.
