### ISSUE TITLE
Cleanup "REST" API

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#528]
The Fractal API, while very useful, is not exactly best practices. We should clean it up in a number of ways, including:

- Pluralize collection endpoints, e.g. `/molecules`, `/keywords`
- Add access to resources by ID, e.g. `/molecules/1234`. Add corresponding methods to Portal, such as `FractalClient.get_collections(id)`. 
- Return appropriate status codes, such as `204` after `DELETE` or `201` after `PUT`. (And change Portal to correctly check status code.) `401` (unauthorized, i.e. not logged in) and `403` (forbidden, i.e. logged in with insufficient permissions) should be used correctly. Also, we return `401` for invalid data blobs (should be `406`?).
- Painful, but `GET` methods should probably not have bodies. (Unclear if this is allowed or not. See e.g. whatwg/fetch#83)
- Going forward, we should also consider implementing new functionality following REST best practices. For example, adding entries to collections should be a `PUT` request. 

REST guides:

- https://medium.com/better-programming/restful-api-designing-guidelines-the-best-practices-39454135f61
- https://www.restapitutorial.com/

@doaa-altarawy

**Comment by doaa-altarawy** [comment]
I'm fully supportive of this refactor.
`GET` without a body.
I'm okay with having just `POST` for add or update, and no need for `PUT`, as many ppl does with REST.
