### ISSUE TITLE
Dashboard - Manager Page

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#537]
**Core Use**
The dashboard requires one (or several) pages dedicated to the observation of manager state and manipulation.

**Required Features**
- List all active managers
- Find recent error messages associated with managers.
- Look in depth at the managers performance over time.
- Display statistics in terms of both jobs and core-hours (where possible)
- Group identical managers in the Manager list
- Bulk restart error-ed jobs in a given queue

**Bonus Features**
- Qualitative indicator of manager health (red, yellow, green?)
- List of recently terminated (or crashed) managers
- Linear/log scale toggle on plots
- How long since most recent task finished?

**Comment by dgasmith** [comment]
@mattwelborn Please edit the above at will. I can reorganize periodically if needed.

**Comment by bennybp** [comment]
Dashboard moved to another repo
