### ISSUE TITLE
Dashboard - User Page

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#538]
**Core Use**
The dashboard requires one page dedicated to user management.

**Required Features**
- List all users
- View user permissions, perhaps in a table formatted similarly to http://docs.qcarchive.molssi.org/projects/QCEngine/en/stable/program_overview.html
- Update permissions
- Update passwords
- CLI link: https://docs.qcarchive.molssi.org/projects/QCFractal/en/stable/server_user.html

**Bonus Features**
- View user-owned managers.
- View user-owned queues, when/if that's implemented.
- User modification features currently implemented in the CLI: create user, change password, change permissions.

**Comment by bennybp** [comment]
Dashboard moved to another repo
