### ISSUE TITLE
Dashboard - Task Page

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#539]
**Core Use**
The dashboard requires one (or more) pages dedicated to tasks and queue management.

**Required Features**

- View queues, grouped by tag.
- View tasks within queues, including STDOUT and STDERR. 
- Search for tasks.
- Modify tasks, either individually or all tasks returned by a search. Modifications include (see #495): 
    - `ERROR` -> `WAITING`
    - `WAITING` <-> `HOLD`
    - `WAITING`, `RUNNING` -> `"KILLED"`
    - `ERROR` -> `FAILED`

**Bonus Features**
- View task by user.
- Change tags on tasks.

**Comment by bennybp** [comment]
Dashboard moved to another repo
