### ISSUE TITLE
Dashboard consumes 100% cpu when connection drops

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCFractal#549]
**Describe the bug**
When the dashboard is successfully connected, then disconnected from the server, its CPU usage rises steadily over time.

**To Reproduce**
Connect the dashboard over and SSH tunnel, then close the SSH connection.

**Expected behavior**
The dashboard should fail gracefully.

**Additional context**

**Comment by dgasmith** [comment]
This is probably related to the error raised when when we cannot connect and Flask simply retrying it repeatedly. We can add a 1 second delay on connection failure perhaps which should reduce the usage substantially.

**Comment by bennybp** [comment]
Dashboard moved to another repo and is being rewritten
