### ISSUE TITLE
DOI Collection Search

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#550]
**Describe the solution you'd like**
Allow `get_collection` to query via a DOI. For example `get_collection(doi="1234:1234")`.

**Describe alternatives you've considered**
Querying off names works well, but alternatives searches for known data is always beneficial and provides another unique ID to the dataset.

This does raise a question if a dataset has multiple DOIs associated with it (S22 where geometries and benchmark values may come from different papers). Perhaps allowing a list of DOIs associated with a collection is wise.

**Comment by mattwelborn** [comment]
Yes, this gets to a larger issue that datasets have DOIs, but so do contributed values within datasets. Probably would be good to have a method that returns all unique citations/dois associated with a dataset.
