### ISSUE TITLE
Optimization and Hessian hybrid procedure  

### ISSUE THREAD

**Issue by jthorton** [MolSSI/QCFractal#554]
**Is your feature request related to a problem? Please describe.**

Currently, it is quite awkward to generate Hessain calculations on an Optimizationdataset after it has completed, this involves periodically checking each task has finished and then adding the new calculation on the final molecule. 

**Describe the solution you'd like**

It would be great to have a procedure that could automatically generate an associated base dataset (with the same name as the optimisation dataset?) that contained the hessian calculations without manual intervention.

**Describe alternatives you've considered**

We could alternatively have a bot per dataset to periodically check the dataset records and submit the new calculations when ready.

**Additional context**

**Comment by dgasmith** [comment]
I wonder if this is popular enough that we should encode it into a service?

@mattwelborn?

**Comment by mattwelborn** [comment]
This feels to me like a good candidate for pipelines?

**Comment by dgasmith** [comment]
It is, but pipelines will never feel as seamless as an object like torsiondrive. Optimization + Something seems popular enough to be worth considering and can be built into things like conformer search where you often want to do low level optimization + high level energy.

**Comment by mattwelborn** [comment]
Do you envision an `OptimizationPlusSinglePointResult`? an `OptimizationPlusSinglePointDataset`? both?

**Comment by dgasmith** [comment]
I think the short here is that we need to implement this at the pipeline layer. We will get too many of these custom objects otherwise.

Timeline is ~3 months for a beta, but that is pretty open depending on what else comes up in the meantime.

**Comment by bennybp** [comment]
I don't have any immediate plans for a pipeline/workflow feature, although I have considered a Optimization + Singlepoint calculation as a simple workflow that covers most use cases.

Superseded by #748
