### ISSUE TITLE
QCArchive top bar to module documentation page not working

### ISSUE THREAD

**Issue by ahurta92** [MolSSI/QCFractal#555]
**Describe the bug**
On QCArchive [](http://docs.qcarchive.molssi.org/en/latest/) the top bar links to the module documentation are not working.  When clicking on any of the links to the module documentation I get the following page:
![image](https://user-images.githubusercontent.com/23067213/73572272-62889200-443e-11ea-9f90-7e710703e0dd.png)

**Comment by dgasmith** [comment]
Thanks for the report. It looks like RTD depreciated a set of links, I have patched this up.
