### ISSUE TITLE
ProcessPoolExecutor Shutdown

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/QCFractal#569]
**Describe the bug**
On Mac the ProcessPoolExecutor sometimes has difficulty shutting down in a timely fashion and occasionally waits for tasks to finish. We can adopt a nuke from above strategy to ameliorate this issue as we actively wish to kill off the workers:

```python
import signal, psutil

def kill_child_processes(parent_pid, sig=signal.SIGTERM):
    try:
        parent = psutil.Process(parent_pid)
    except psutil.NoSuchProcess:
        return
    children = parent.children(recursive=True)
    for process in children:
        process.send_signal(sig)
```

**Comment by bennybp** [comment]
No longer applicable as the manager is always Parsl-based now
