### ISSUE TITLE
Is there a way to mark "INCOMPLETE" records as "ERRORED" (or re-run them)?

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#599]
**Describe what you are trying to achieve**

The `"OpenFF Fragmenter Validation 1.0"` `TorsionDriveDataset` has several `"INCOMPLETE"` `OptimizationRecords`. We believe these to be broken in some way, though it is not clear from the records how; the associated tasks have been running for weeks, and this is unexpected.

Is there a way to mark these `"INCOMPLETE"` records as `"ERROR"` cases? Or, more directly, is there a way to call `client.modify_tasks(operation='restart', base_result='<optimization_record_id>')` on a task that is `"INCOMPLETE"` to mark it for re-run?

Finally, how does the fact that these `OptimizationRecords` are generated using a `TorsionDrive` service impact our approach? Should we pursue a different pathway for dealing with potentially hung tasks? For example, is there a way to call `client.modify_services(operation='restart', procedure_id='<running_torsion_drive_id>')` on a `"RUNNING"` `TorsionDriveRecord` to mark it for re-run?

**Comment by bennybp** [comment]
v0.50 should fix all these issues. Resetting records is more powerful, and the bug allowing this to happen is hopefully fixed. We also have an `invalid` and `cancelled` statuses that might be appropriate.
