### ISSUE TITLE
Add compute tags to tasks after submission?

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#600]
In troubleshooting tasks that ERROR or hang at INCOMPLETE for some time, it would be useful to be able to route these tasks to a `Manager` running on a machine with greater local visibility e.g. log and output analysis. 

Currently, we can do this by restricting our running `Manager`s to entrap the tasks in question, but this strategy falls apart when many tasks are in the queue. As another alternative, we currently attempt to reproduce the observed behavior on a local QCArchive instance with tasks configured in the same way. This may take a long time, as for `TorsionDrive`s, because the failure may show up only on a task much later in the execution sequence.

Having this capability would give us a quick diagnostic route for problem tasks. Allowing execution tags to be added to tasks that have already been submitted would enable a `Manager` with matching tags to grab only those tasks, which is the behavior desired above.

**Comment by bennybp** [comment]
Ability to modify tags was added in v0.14, so I think that solves the issue.
