### ISSUE TITLE
Remove casting of indices to lowercase in dataset submission

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#650]
**Describe the bug**

The indices used for datasets submitted to QCArchive are forced to lowercase, and this can cause problems for e.g. SMARTS used as the indices, in which two different SMARTs get lowered to the same index. 

If there is no explicit value added from lowercasing indices, I propose we eliminate it. This change shouldn't impact existing datasets already in the database, but would perhaps impact user access for users accustomed to case-insensitive indexing.

**Comment by bennybp** [comment]
Dataset entries in v0.50 are now case sensitive
