### ISSUE TITLE
Allow increase of `maxiter` for OptimizationDatasets

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#651]
**Is your feature request related to a problem? Please describe.**

It is often the case that the initial `maxiter` setting for geometry optimization datasets is set too low on submission, resulting in many `OptimizationRecord`s that will never complete unless the `maxiter` is set higher. 

**Describe the solution you'd like**

Because this setting is entirely a compute parameter, and has no bearing on the final result (except for completion, as noted), we would like to be able to alter this on an existing `OptimizationDataset`, or at the very least increase it, after submission.

This may be tricky, as existing tasks associated with each `OptimizationRecord` would need to be either altered or replaced with the new `maxiter`.

**Describe alternatives you've considered**

Currently, we often re-submit the compute spec with a higher number of iterations specified on the dataset. This is rather wasteful, as it will re-compute for cases already completed in addition to those that haven't.

**Additional context**

**Comment by bennybp** [comment]
I don't see a way to do this with individual records. However, you can now set `additional_keywords` on entries in an OptimizationDataset. These are merged with the specification keywords when creating records for a particular entry. So those records would be recalculated, but at least already-completed entries wouldn't be recomputed.
