### ISSUE TITLE
Adopt Python support schedule from NEP 29

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#659]
In order to accelerate development and reduce the compatibility burden on developers, I propose we officially adopt the drop schedule for Python and NumPy supported versions detailed in [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).

As for immediate action, adoption of this proposal entails dropping support for:
- Python <= 3.6
- Numpy <= 1.16

We are currently not executing CI for Python 3.6, but we may still be building conda packages for this.

**Comment by bennybp** [comment]
Absolutely on board with this. Some of the newer modifications I have been making will require Python 3.7
