### ISSUE TITLE
Can dataset `get_records` drop missing records

### ISSUE THREAD

**Issue by jthorton** [MolSSI/QCFractal#706]
**Is your feature request related to a problem? Please describe.**
It would be helpful if the dataset `get_records` method could drop missing records when using the status keyword as currently, it returns the index and NaN for the record even when I request only complete records. This would stop me from having to filter the query result again. 

Some code to reproduce
```python
from qcportal import FractalClient
client = FractalClient()
ds = client.get_collection("dataset", "OpenFF BCC Refit Study COH v1.0")
dataset_specs = {
                spec: {"method": method, "basis": basis, "program": program}
                for _, program, method, basis, spec in ds.data.history
            }
query = ds.get_records(**dataset_specs["resp-2-vacuum"], status=["complete"])
query
```
>  CC(=O)c1ccccc1-0	ResultRecord(id='32651733', status='COMPLETE')
...	...
C(C#N)SC1=NN=C(N1)N	NaN
CCCCSC1=NN=C(S1)N-0	NaN
CCCCSC1=NN=C(S1)N-1	NaN
CCCCSC1=NN=C(S1)N-2	NaN
CCCC1CCCNC1	NaN

**Describe the solution you'd like**
To only return records with the requested status and to drop not yet computed records.

**Describe alternatives you've considered**
I can filter the query myself but I think it would be faster to do this during the database search particularly for larger datasets and would mean sending less data back to the user. 

**Additional context**

**Comment by bennybp** [comment]
Getting records in a singlepoint dataset has completely changed in v0.50, so this isn't applicable anymore
