### ISSUE TITLE
Dataset status 

### ISSUE THREAD

**Issue by jthorton** [MolSSI/QCFractal#707]
**Is your feature request related to a problem? Please describe.**
Datasets are unlike the other collections and are missing many nice features! I think it would be good to add a status function that works similarly to the other collections.

**Describe the solution you'd like**
Add a simple status function that gives information on the current status of each compute spec applied to the dataset similar to optimisation and torsiondrive datasets. 

**Describe alternatives you've considered**
We currently have an automated github action to do this which has to query the database for each spec on the dataset and then tabulates the status of the dataset. However, it would probably be faster to do this in the server and send a final data frame back to the user. 

**Additional context**

**Comment by bennybp** [comment]
This is absolutely going into the next major version. The new structure makes this much faster and applicable to all types datasets.

**Comment by bennybp** [comment]
v0.50 does indeed have a unified `status()` interface that works with all datasets!
