### ISSUE TITLE
`set` causes issues in `qcfractal.interface.collections.Dataset` objects

### ISSUE THREAD

**Issue by cwognum** [MolSSI/QCFractal#722]
**Describe the bug**
In the most recent release (`v0.15.8.1`), trying to use `get_values()` on a Dataset collection (`qcfractal.interface.collections.Dataset`) fails due to an index or columns being a set. These are some examples I found:
- [qcfractal/interface/collections/dataset.py#L724](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/dataset.py#L724)
- [qcfractal/interface/collections/dataset.py#L1465](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/dataset.py#L1465)
-  [qcfractal/interface/collections/dataset.py#L1485](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/dataset.py#L1485)

In other places, it currently throws a `FutureWarning` due to indexing (i.e. `df.loc[...]`) with a set:
- [qcfractal/interface/collections/dataset.py#L273](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/dataset.py#L273)
- [qcfractal/interface/collections/dataset.py#L748](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/dataset.py#L748)
- [qcfractal/interface/collections/dataset.py#L1459](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/dataset.py#L1459)
- [qcfractal/interface/collections/dataset.py#L1534](https://github.com/MolSSI/QCFractal/blob/master/qcfractal/interface/collections/dataset.py#L1534)

**To Reproduce**
Follow the tutorial in the docs: [here](http://docs.qcarchive.molssi.org/projects/QCFractal/en/stable/quickstart.html?highlight=FractalClient#Computing-with-collections).

**Expected behavior**
No error to be thrown, but rather that a DataFrame is returned successfully. 

**Additional context**
Related issue: https://github.com/MolSSI/QCFractal/issues/591

**Comment by bennybp** [comment]
This is no longer applicable in v0.50, which doesn't use pandas or 'history' internally anymore. Although the interface has changed quite a bit.

See the new (always in-progress) docs: https://molssi.github.io/QCFractal
