### ISSUE TITLE
[next branch] what is the difference between `qcfractal-manager` and  `qcfractal-compute-manager`

### ISSUE THREAD

**Issue by hadim** [MolSSI/QCFractal#724]
Looking at the code they both seem to start a `ComputeManager()` object but with different types of configurations.

My question is whether one is the legacy or whether both are legit and simply cover different use cases?

ping @bennybp

**Comment by bennybp** [comment]
The one that is started with `qcfractal-manager` (in `qcfractal_manager_cli.py`) is legacy. This one tried to support different backends, but ended up somewhat complex. It is being left in (and function) for a little while.

The newer version `qcfractal-compute-manager` (slightly better name I hope, although confusing at the moment) supports only Parsl,  but that will allow for some more interesting features in the future.

The new `qcfractal-compute-manager` also supports handling the QM packages being in different conda envs and apptainer/singularity containers (experimentally). I hope to write some docs soon...

**Comment by hadim** [comment]
Thanks for the heads-up, I will try moving to `qcfractal-compute-manager` then.
