### ISSUE TITLE
FractalClient incompatible with pydantic 2

### ISSUE THREAD

**Issue by IgnacioJPickering** [MolSSI/QCFractal#735]
**Describe the bug**
FractalClient can't be imported from qcportal with pydantic v2

**To Reproduce**
``from qcportal import FractalClient`` in an environment with pydantic v2

**Expected behavior**
FractalClient should work, or pydantic version should be pinned to 1.10

**Additional context**
currently installing qcportal from conda-force will install the latest version of pydantic, since it is not pinned, but qcportal seems to be incompatible with pydantic 2.0

**Comment by bennybp** [comment]
v0.15 of qcportal should be pinned to pydantic 1 (at least the conda packages are).

We are working on making v0.50 working with pydantic, although it's a big undertaking, requiring migrating qcelemental as well. See #736
