### ISSUE TITLE
Use Mongoengine as an ODM for MongoDB

### ISSUE THREAD

**Issue by doaa-altarawy** [MolSSI/QCFractal#76]
We would like to have the option to use ODM (Object-Document mapper, like ORM) when handling MongoDB. This will move some of the business logic and validation, currently implemented in the monogo_socket, into the Mongoengine.

This addition will require some changes in the design of the indexes and collections relations in the current design to be able to handle it efficiently in the Mongoengine layer.

**Comment by dgasmith** [comment]
The `task_queue` collection needs an index for `created_on`. Currently `queue_get_next` queries become very slow as the total task lists grows due to no indices there.

**Comment by doaa-altarawy** [comment]
I'll add an index on the status too.
