### ISSUE TITLE
Diagram indicating result flow from compute managers to server has arrow wrong direction 

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#788]
**Describe the bug**

The diagram indicating result flow from compute managers to the server appears to have the arrow pointing in the wrong direction: https://molssi.github.io/QCFractal/overview/tasks_services.html#tasks

**Comment by bennybp** [comment]
Well I don't know how that escaped notice for so long :)

**Comment by bennybp** [comment]
Fixed in #789
