### ISSUE TITLE
`ConnectionRefusedError` after using an idle client some time later

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#790]
**Describe the bug**

After leaving a `PortalClient` instance idle for approx. 24hrs, using `list_datasets()` yields:

```
ConnectionRefusedError: Unable to refresh JWT authorization token! This is a server issue!!
```

Creating a new client instance resolved the issue, but this is still unexpected behavior.

Is this a symptom of using two tokens (an "access" token and a "refresh" token) with separate expirations for auth? Or is it something else?

**Comment by bennybp** [comment]
No there was a bug in some of the JWT handling. Also reported in #784, fixed in PR #783.

I just increased the expiration time, which should keep that at bay for a bit until the next release (should be soon).
