### ISSUE TITLE
Add `TorsionDriveRecord.status` method giving status counts of its children `OptimizationRecord`s

### ISSUE THREAD

**Issue by dotsdl** [MolSSI/QCFractal#791]
Currently, getting the status counts of the `OptimizationRecord`s making up a `TorsionDriveRecord` appears to require iterating through each of these `OptimizationRecord`s individually. 

Instead of this, it would be useful for e.g. [generating reports like these](https://github.com/openforcefield/qca-dataset-submission/pull/281#issuecomment-1044470615)) to be able to get these status counts for each `TorsionDriveRecord` with a `.status` method call, similar to that on `TorsionDriveDataset`, that yields these counts. The API point that serves these could likely get these counts with a single fast query on the DB.

**Comment by bennybp** [comment]
Added in #792
