### ISSUE TITLE
Client add_compute should throw if molecule not found

### ISSUE THREAD

**Issue by Lnaden** [MolSSI/QCFractal#81]
**Describe the bug**
The current `add_compute` as part of the client will work if you give it a molecule ID already in the server or a fully defined molecule which will be inserted into the server.

The corner case is when you give it a molecule ID which is NOT in the server already, the current function will not error and will simply return an empty return object. We should change this to instead throw an error indicating which IDs were missing.

**Comment by dgasmith** [comment]
Not quite as simple as just throwing an error. Imagine if a user submits `client.add_compute(... moluleces=["known_id", "unknown_molecule!"])`. We can:
 - Not accept any new compute and return an error
 - Only accept the valid compute and return a part success, part failure.
   - Currently we return a `{"submitted": , "completed"}` dictionary of task id's for future use. We can add a "error" field here if we with the problem molecules? This would require users to actively check the returned dictionary to see if anything went wrong.
   - This also applied to things like if the "options_name" field is not found. Everything will need to return with an error.

@doaa-altarawy do you have thoughts on how we should handle this as well?
