### ISSUE TITLE
Is QM7b no longer downloadable via API?

### ISSUE THREAD

**Issue by kvkarandashev** [MolSSI/QCFractal#828]
I have an old script that used to be able to download QM7b in desired format directly from `api.qcarchive.molssi.org`. I have not run it for years, tried to start it again only to realize API's coding has changed completely. As far as I understand the new API based on the Python code (couldn't find documentation that was not outdated) I can view datasets I can download with it via:
```
import qcportal as ptl

client = ptl.PortalClient("https://api.qcarchive.molssi.org")

d=client.list_datasets()

for i in d:
    print(i)
```
Is there some other way to download QM7b that I'm not seeing? I saw it on `https://qcarchive.molssi.org/apps/ml_datasets/`, but would prefer to have API download functional as well.

**Comment by bennybp** [comment]
The url for that dataset has changed if you are using the new client (which it looks like you are doing). The new URL is `https://ml.qcarchive.molssi.org`

So just use that when constructing the client.

```python
client = ptl.PortalClient("https://ml.qcarchive.molssi.org")
```

I just confirmed that the data does appear to exist there. You can also check it with your browser:
https://ml.qcarchive.molssi.org/api/v1/datasets

**Comment by kvkarandashev** [comment]
Thank you for the quick reply! Yes, I see the dataset is available there now.
