### ISSUE TITLE
Documentation Example Page is Down

### ISSUE THREAD

**Issue by jhmlam** [MolSSI/QCFractal#862]
**Describe what you are trying to achieve**

Dear Colleagues, 
The webpage "https://qcarchive.molssi.org/examples/" give 404.
I wonder if there is a new webpage or if the same/similar contents are stored elsewhere.  
Thank you.
Best,
Jordy
**Describe methods you have considered**

Edge Browser. Firefox Browser.

**Comment by mattwthompson** [comment]
The docs are now at https://molssi.github.io/QCFractal/
