### ISSUE TITLE
More flexible way to specify DB connection settings

### ISSUE THREAD

**Issue by doaa-altarawy** [MolSSI/QCFractal#87]
In the CLI, I suggest allowing the option to use the host, port, and DB name as separate inputs to QCFractal server as they are very convenient and easier to format than squashing user/pass/host/port/DB_name in a URIs. We can still keep the option URI too.
The common user would want to only choose a DB name.

**Comment by dgasmith** [comment]
Lets wait on #78 before moving this in as this may change the constructors.

**Comment by dgasmith** [comment]
This no longer a relevant issue.
