### ISSUE TITLE
OSError: File: molecules/hooh.json not found 

### ISSUE THREAD

**Issue by ChayaSt** [MolSSI/QCFractal#97]
**Describe the bug**
When trying to test qcfractal integration with fragmenter, we get the error `OSError: File molecules/hooh.json not found`
https://travis-ci.org/openforcefield/fragmenter/jobs/455654228#L833

**Additional context**
@dgasmith added the integration test here:
https://github.com/openforcefield/fragmenter/pull/24

**Comment by dgasmith** [comment]
Kind of odd, this likely only happens when we install. `recursive-include qcfractal/interface/data *.json` in our MANIFEST should pick this up. I wonder if this problem is a peculiarity of using `pip install git+git...`.
