### ISSUE TITLE
Task submission use cases

### ISSUE THREAD

**Issue by doaa-altarawy** [MolSSI/QCFractal#98]
This is the possible use cases when submitting a task to the queue.

### Case 1: Single Result

The user whould like to find or computer a result identified by a specific:
- 'program',
- 'driver',
- 'method',
- 'basis',
- 'molecule', 
- 'options'.

The user will create the molecule and store it in the Database, and has its ID.
For the options, they should find it in the options table?? (TODO) 

Ques: is the common case to have many of such single results at the same time?

The following is the logical steps to be done:

- Search results table to see if it exists using the data s/he has (flaged with include_queued=True).
   1. If found and status=COMPLETE) then return the results data.
   2. if found but status=INCOMPLETE, then merge hooks and return the job ID and result ID or a top 
       level procedure ID
   3. If not found at all, then add a result or a top level procedure, and submit a task into the queue.

This should be mostly done in the socket itself.

When a task is done:
1. if it's a simple result, store the data in task.base_result, then call the hooks.
2. if it's a procedure, "create" the children results, and then update the procedure object (it's id is in task.base_result) with those ids. Next, call the hooks.

**Comment by dgasmith** [comment]
I think the heart of this PR has been long closed. @doaa-altarawy Please let me know if you wish to reopen.
